/**
 * The phoneme inventory — sounds, with no writing system attached.
 *
 * This is the engine's canonical layer, and the reason every script can be a
 * peer. The siksa rules are PHONOLOGICAL: they ask whether a sound is a
 * sibilant, is voiced, belongs to a varga. A system whose substrate is a script
 * will always privilege that script, so the substrate here is not a script.
 *
 * `PhonemeId` is spelled with Latin letters because a human has to be able to
 * read this table. It is an IDENTIFIER, not a rendering: IAST supplies its own
 * mapping in `scripts/iast.ts` like every other writing system, and removing
 * IAST from the registry does not stop the engine deriving.
 *
 * GENERATED by tools/gen-script-modules.mjs. Do not edit by hand.
 */

export type PhonemeType = 'vowel' | 'consonant' | 'special';

export type Varga =
  | 'ka' | 'ca' | 'ta-retroflex' | 'ta-dental' | 'pa' | 'misc' | 'sibilant';

/** A phoneme's stable key. An identifier, not a writing system. */
export type PhonemeId = string;

export interface Phoneme {
  readonly id: PhonemeId;
  readonly type: PhonemeType;
  /** For consonants: the varga, which several rules and the keyboard read. */
  readonly varga?: Varga;
  readonly label?: string;
}

export const PHONEME_INVENTORY: readonly Phoneme[] = [
  { id: "a", type: "vowel" },
  { id: "ā", type: "vowel" },
  { id: "i", type: "vowel" },
  { id: "ī", type: "vowel" },
  { id: "u", type: "vowel" },
  { id: "ū", type: "vowel" },
  { id: "ṛ", type: "vowel" },
  { id: "ṝ", type: "vowel" },
  { id: "ḷ", type: "vowel" },
  { id: "ḹ", type: "vowel" },
  { id: "e", type: "vowel" },
  { id: "ai", type: "vowel" },
  { id: "o", type: "vowel" },
  { id: "au", type: "vowel" },
  { id: "k", type: "consonant", varga: "ka" },
  { id: "kh", type: "consonant", varga: "ka" },
  { id: "g", type: "consonant", varga: "ka" },
  { id: "gh", type: "consonant", varga: "ka" },
  { id: "ṅ", type: "consonant", varga: "ka" },
  { id: "c", type: "consonant", varga: "ca" },
  { id: "ch", type: "consonant", varga: "ca" },
  { id: "j", type: "consonant", varga: "ca" },
  { id: "jh", type: "consonant", varga: "ca" },
  { id: "ñ", type: "consonant", varga: "ca" },
  { id: "ṭ", type: "consonant", varga: "ta-retroflex" },
  { id: "ṭh", type: "consonant", varga: "ta-retroflex" },
  { id: "ḍ", type: "consonant", varga: "ta-retroflex" },
  { id: "ḍh", type: "consonant", varga: "ta-retroflex" },
  { id: "ṇ", type: "consonant", varga: "ta-retroflex" },
  { id: "t", type: "consonant", varga: "ta-dental" },
  { id: "th", type: "consonant", varga: "ta-dental" },
  { id: "d", type: "consonant", varga: "ta-dental" },
  { id: "dh", type: "consonant", varga: "ta-dental" },
  { id: "n", type: "consonant", varga: "ta-dental" },
  { id: "p", type: "consonant", varga: "pa" },
  { id: "ph", type: "consonant", varga: "pa" },
  { id: "b", type: "consonant", varga: "pa" },
  { id: "bh", type: "consonant", varga: "pa" },
  { id: "m", type: "consonant", varga: "pa" },
  { id: "y", type: "consonant", varga: "misc" },
  { id: "r", type: "consonant", varga: "misc" },
  { id: "l", type: "consonant", varga: "misc" },
  { id: "v", type: "consonant", varga: "misc" },
  { id: "ś", type: "consonant", varga: "sibilant" },
  { id: "ṣ", type: "consonant", varga: "sibilant" },
  { id: "s", type: "consonant", varga: "sibilant" },
  { id: "h", type: "consonant", varga: "misc" },
  { id: "ḻ", type: "consonant", varga: "misc" },
  { id: "ṁ", type: "special", label: "anusvāra" },
  { id: "ḥ", type: "special", label: "visarga" },
  { id: "'", type: "special", label: "avagraha" },
  { id: "।", type: "special", label: "daṇḍa" },
  { id: "॥", type: "special", label: "double daṇḍa" },
];

/** Phonemes that take a matra when they follow a consonant. */
export const NUCLEUS_IDS: readonly PhonemeId[] = [
  "a",
  "ā",
  "i",
  "ī",
  "u",
  "ū",
  "ṛ",
  "ṝ",
  "ḷ",
  "ḹ",
  "e",
  "ai",
  "o",
  "au",
];

export const PHONEME_BY_ID: ReadonlyMap<PhonemeId, Phoneme> = new Map(
  PHONEME_INVENTORY.map((p) => [p.id, p]),
);
