#!/usr/bin/env node
/**
 * Generate the `@font-face` block from the manifest.
 *
 * Generated rather than hand-written for the usual reason: 71 files is more
 * than anyone keeps in step by hand, and a `@font-face` pointing at a file that
 * is not there fails SILENTLY — the browser moves to the next face in the stack
 * and the text renders in something else. Nobody notices until the diacritics
 * look wrong.
 *
 * Two layers per text family, and the order matters:
 *
 *   1. the SUBSET files, with a `unicode-range`, so a page loads ~60 KB rather
 *      than 800 KB for the letters it actually uses;
 *   2. the COMPLETE file, with no range, listed after — so anything outside the
 *      subsets (the candrabindu at U+0310, above all) still resolves in the
 *      same family rather than falling through to a different one.
 *
 *   node tools/fonts/gen-css.mjs
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  DEFAULT_SUBSETS, FAMILIES, FULL_FILES, fileName, fullName,
} from './manifest.mjs';

const OUT = 'assets/fonts';

/* The ranges Fontsource declares. Written out so the generated CSS is
   self-contained and does not need the network to be regenerated. */
const RANGE = {
  latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,'
       + 'U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,'
       + 'U+2215,U+FEFF,U+FFFD',
  'latin-ext': 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,'
       + 'U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,'
       + 'U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  devanagari: 'U+0900-097F,U+1CD0-1CF9,U+200C-200D,U+20A8,U+20B9,U+20F0,'
       + 'U+25CC,U+A830-A839,U+A8E0-A8FF,U+11B00-11B09',
  telugu: 'U+0951-0952,U+0964-0965,U+0C00-0C7F,U+1CDA,U+1CF2,U+200C-200D,U+25CC',
  tamil: 'U+0964-0965,U+0B82-0BFA,U+200C-200D,U+20B9,U+25CC',
};

const faces = [];

for (const family of FAMILIES) {
  const subsets = family.subsets ?? DEFAULT_SUBSETS;
  const styles = family.italics ? ['normal', 'italic'] : ['normal'];
  for (const subset of subsets) {
    for (const weight of family.weights) {
      for (const style of styles) {
        faces.push({
          name: family.name,
          file: fileName(family.id, subset, weight, style),
          weight, style,
          range: RANGE[subset],
          format: 'woff2',
        });
      }
    }
  }
}

/* The complete files last: a `@font-face` with no `unicode-range` matches
   everything, so it must come after the ranged ones or it would win for
   codepoints the small files were meant to serve. */
for (const key of Object.keys(FULL_FILES)) {
  const [id, variant = 'normal'] = key.split(':');
  const family = FAMILIES.find((f) => f.id === id);
  if (family === undefined) continue;
  const bold = variant === '700';
  faces.push({
    name: family.name,
    file: fullName(id, variant),
    weight: bold ? 700 : (variant === 'italic' ? 400 : '400 700'),
    style: variant === 'italic' ? 'italic' : 'normal',
    range: undefined,
    format: 'truetype',
  });
}

const css = `/* GENERATED by tools/fonts/gen-css.mjs from tools/fonts/manifest.mjs.
 * Do not edit.
 *
 * ${faces.length} faces. Every file is vendored in this directory and
 * redistributed under the licence recorded in LICENSES.md.
 *
 * Subset files carry a \`unicode-range\` so a page loads only what it needs.
 * The complete text faces come LAST and carry no range, so a codepoint outside
 * every subset — the candrabindu at U+0310, in particular — still resolves
 * within the same family instead of falling through to whatever the system has.
 */

${faces.map((f) => `@font-face {
  font-family: '${f.name}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./${f.file}') format('${f.format}');${f.range === undefined ? '' : `
  unicode-range: ${f.range};`}
}`).join('\n\n')}
`;

writeFileSync(join(OUT, 'fonts.css'), css);
console.log(`\n  ${faces.length} @font-face rules -> ${OUT}/fonts.css\n`);
