"""
THE MANTRA LINE'S ADVANCE WIDTHS — how wide each letter of an IAST line is in
his `Translit` face, so a line can be measured without a browser.

His ruling (2026-10-02): "breaking the lines sooner, dividing them nicely in
consistent size ... Sometimes longer, sometimes shorter, but more consistent,
no need to fill the entire line". A line that will not fit the column is
divided where it is written (`packages/layout/src/line-fit.ts`), so the PDF,
the `.docx` and the app all show the same lines — and that needs the width of
a line in points before anything is drawn.

Read from ARIMO, which has Arial's advance widths exactly (metric-compatible,
Apache-2.0, vendored in `assets/fonts/`), and the daṇḍa from our own measured
copy of his Mangal's (`siksamitra-danda`). Combining marks have no advance and
are left out: a reader of the table counts them as nothing.

    .venv/Scripts/python tools/fonts/widths.py      # writes packages/tokens/src/mantra-widths.ts
"""
from fontTools.ttLib import TTFont

FACES = [
    'assets/fonts/arimo-latin-400-normal.woff2',
    'assets/fonts/arimo-latin-ext-400-normal.woff2',
]
DANDA = 'assets/fonts/siksamitra-danda-400-normal.ttf'
OUT = 'packages/tokens/src/mantra-widths.ts'

# Every letter an IAST mantra line writes, its signs, and what his lines carry besides.
LETTERS = (
    'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    'āīūṛṝḷḹṃṁḥñṅṇṭḍśṣēōḻĀĪŪṚṜḶḸṂṀḤÑṄṆṬḌŚṢĒŌḺ'
    "  -'’.,;:|¦()[]?!/·–—ˎʼ"
)


def advances(path):
    font = TTFont(path)
    em = font['head'].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font['hmtx']
    return {ch: hmtx[cmap[ord(ch)]][0] / em for ch in LETTERS + '।॥' if ord(ch) in cmap}


widths = {}
for face in FACES:
    for ch, w in advances(face).items():
        widths.setdefault(ch, w)
danda = advances(DANDA)
missing = [ch for ch in LETTERS if ch not in widths]
if missing:
    raise SystemExit(f'no advance for: {missing!r}')


def key(ch):
    return repr(ch) if ch not in ("'", '\\') else '"' + ch + '"'


def js(ch):
    if ch == "'":
        return '"\'"'
    if ord(ch) < 0x20 or ch in (' ',):
        return "'\\u%04x'" % ord(ch)
    return "'" + ch + "'"


rows = [f'  [{js(ch)}, {widths[ch]:.4f}],' for ch in LETTERS]
lines = [
    '/**',
    ' * The mantra line\'s advance widths, in ems of its face — GENERATED by',
    ' * `tools/fonts/widths.py` from Arimo (Arial\'s widths exactly) and the daṇḍa',
    ' * of `siksamitra-danda` (his Mangal\'s). Do not edit; run the script.',
    ' *',
    ' * Combining marks — the svaras, the macron below — have no advance and are',
    ' * not here: a reader counts them as nothing (`line-fit.ts`).',
    ' */',
    'export const MANTRA_ADVANCE: ReadonlyMap<string, number> = new Map([',
    *rows,
    f"  ['।', {danda.get(chr(0x964), 0.4):.4f}],",
    f"  ['॥', {danda.get(chr(0x965), 0.6):.4f}],",
    ']);',
    '',
    '/** A letter the table does not have: Arial\'s own average, its lower case. */',
    f"export const MANTRA_ADVANCE_FALLBACK = {sum(widths[c] for c in 'abcdefghijklmnopqrstuvwxyz') / 26:.4f};",
    '',
]
open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
print(f'{OUT}: {len(rows) + 2} advances')
