/**
 * Recovering a verse's SOURCE from the marks it already carries.
 *
 * Every document this program inherited was generated by an offline script
 * that kept only its output: 573 verses of marked tokens with no record of the
 * letters they were derived from. That is why they could not be edited — the
 * editor re-derives, and there was nothing to re-derive from.
 *
 * This is the inverse. It reconstructs the two strings a source layer holds:
 *
 *   `lines`     the PRE-sandhi letters, which is what the rules take as input
 *   `accented`  the same letters carrying the accents as combining marks,
 *               which is what an accented printed witness looks like
 *
 * IT IS NOT A PROOF OF ANYTHING BY ITSELF. Running it and then deriving from
 * its output tests that this function and the pipeline are mutual inverses —
 * which is exactly what "the document is regenerable" means, and is not the
 * same as agreeing with a printed edition. Where the two disagree, the verse
 * keeps no source layer and stays frozen; that is `sm attach-src`'s job, and
 * it reports the count.
 *
 * Two things have to be undone, and ONLY these two:
 *
 *   - a `change` letter goes back to its trigger (`ṁ` or `ḥ`), because the
 *     holdings run before the anusvāra/visarga substitutions;
 *   - a `pause` token is dropped, because the bīja and vowel-hiatus pauses are
 *     placed by the engine and re-emitting one as `|` would put a saṁyukta
 *     barrier into the source that the author never wrote.
 *
 * Everything else on a unit — `sup`, `sbhakti`, `candra`, `hold` — is derived,
 * and none of it belongs in the letters.
 */
import { unlengthen } from './rules/rigveda.js';
import type { ChantSvara, ChantToken, ChantUnit } from '@siksamitra/format';
import { typedAs } from './changes.js';
import { norm } from './normalize.js';
import { witnessLine } from './rules/witness.js';


/** A substituted letter back to what was typed — `typedAs`, the one answer. */
const undoChange = (u: ChantUnit): string => (u.change === true ? u.was ?? typedAs(u.c) ?? u.c : u.c);

export interface InvertedSource {
  /** The pre-sandhi letters, one string per displayed line. */
  lines: string[];
  /** The same letters with the accents written back as combining marks. */
  accented: string[];
  /** Whether any accent was found at all — a prose text has none, and giving
   *  it an `accented` layer would claim a witness that does not exist. */
  accents: number;
}

/** Reconstruct a verse's source from its tokens. */
export interface InvertOptions {
  /**
   * Was the verse marked under a register that LENGTHENS the svarita — the
   * Ṛgveda's (`svara.lengthening`)? Then it is read back through
   * `unlengthen`: the accent a person TYPES is the plain svarita on the vowel,
   * and the dīrgha-svarita and the overline are what the rules made of it.
   *
   * Asked of the register's setting and never of its recension: a Ṛgvedic
   * text with lengthening switched off — the Pūjā Vidhi — has dīrgha-svaritas
   * that were TYPED, and reading them back as lengthened svaritas took them
   * off. `lengthens(profile)` answers it.
   */
  lengthened?: boolean;
}

export function invertVerse(tokens: readonly ChantToken[], opts: InvertOptions = {}): InvertedSource {
  if (opts.lengthened === true) tokens = unlengthenTokens(tokens);
  const lines: string[] = [];
  const accented: string[] = [];
  let plain = '';
  let witness: { c: string; svara?: ChantSvara }[] = [];
  let accents = 0;

  /*
   * NORMALISED, both of them. A stored source line must be canonical — `norm`
   * idempotent on it — because the whole override addressing scheme is offsets
   * into it (see `rebase.ts` in `@siksamitra/edit`). Returning the raw
   * reconstruction instead meant the first no-op edit re-normalised the line,
   * every offset after the change moved, and three hand-placed marks were
   * reported lost for an edit that inserted nothing.
   */
  const flush = (): void => {
    if (plain.trim() === '') return;
    lines.push(norm(plain));
    accented.push(norm(witnessLine(witness)));
    plain = '';
    witness = [];
  };
  const put = (s: string): void => {
    plain += s;
    witness.push({ c: s });
  };

  for (const t of tokens) {
    if (t.t === 'syl') {
      for (const u of t.units) {
        const c = undoChange(u);
        plain += c;
        if (u.svara === undefined) witness.push({ c });
        else {
          witness.push({ c, svara: u.svara });
          accents += 1;
        }
      }
    }
    /* One space, however many the stream has: a pause the rules placed stands
       between two (`rya ␣ | ␣ ā`), and it is not in what was typed, so taking
       it out must not leave `rya  ā` behind. */
    else if (t.t === 'sp') { if (!plain.endsWith(' ')) put(' '); }
    else if (t.t === 'br') {
      lines.push(norm(plain));
      accented.push(norm(witnessLine(witness)));
      plain = '';
      witness = [];
    }
    /*
     * NOT PADDED. `lex` splits a part at a structure boundary by itself, so
     * `||3||` lexes as daṇḍa · number · daṇḍa with no help — and the source
     * then reads exactly as the document does. Padding it was what put 176
     * verses' worth of spaces into the derived stream that the original never
     * had.
     */
    else if (t.t === 'danda') put(t.s === '॥' ? '||' : '|');
    else if (t.t === 'bar') put('¦');
    else if (t.t === 'num') put(t.s);
  }
  flush();

  return { lines, accented, accents };
}

/** Every syllable's units through `unlengthen`, as one sequence — rule 2 moves
 *  an accent from a nasal back to the vowel before it, which may be the last
 *  letter of the previous syllable. */
function unlengthenTokens(tokens: readonly ChantToken[]): ChantToken[] {
  const flat = tokens.flatMap((t) => (t.t === 'syl' ? t.units.map((u) => ({ ...u })) : []));
  const back = unlengthen(flat);
  let k = 0;
  return tokens.map((t) => {
    if (t.t !== 'syl') return t;
    const units = t.units.map((u) => {
      const b = back[k++]!;
      const { svara: _drop, candra: _c, change: _ch, ...rest } = u;
      return {
        ...rest, c: b.c,
        ...(b.svara === undefined ? {} : { svara: b.svara as ChantSvara }),
        ...(b.candra === true ? { candra: true } : {}),
        ...(b.change === true ? { change: true } : {}),
        ...(u.was === undefined ? {} : { was: u.was }),
      };
    });
    return { ...t, units };
  });
}
