/**
 * Recovering a verse's SOURCE from the marks it already carries.
 *
 * Every document this program inherited was generated by an offline script
 * that kept only its output: 573 verses of marked tokens with no record of the
 * letters they were derived from. That is why they could not be edited — the
 * editor re-derives, and there was nothing to re-derive from.
 *
 * This is the inverse. It reconstructs the two strings a source layer holds:
 *
 *   `lines`     the PRE-sandhi letters, which is what the rules take as input
 *   `accented`  the same letters carrying the accents as combining marks,
 *               which is what an accented printed witness looks like
 *
 * IT IS NOT A PROOF OF ANYTHING BY ITSELF. Running it and then deriving from
 * its output tests that this function and the pipeline are mutual inverses —
 * which is exactly what "the document is regenerable" means, and is not the
 * same as agreeing with a printed edition. Where the two disagree, the verse
 * keeps no source layer and stays frozen; that is `sm attach-src`'s job, and
 * it reports the count.
 *
 * Two things have to be undone, and ONLY these two:
 *
 *   - a `change` letter goes back to its trigger (`ṁ` or `ḥ`), because the
 *     holdings run before the anusvāra/visarga substitutions;
 *   - a `pause` token is dropped, because the bīja and vowel-hiatus pauses are
 *     placed by the engine and re-emitting one as `|` would put a saṁyukta
 *     barrier into the source that the author never wrote.
 *
 * Everything else on a unit — `sup`, `sbhakti`, `candra`, `hold` — is derived,
 * and none of it belongs in the letters.
 */
import type { ChantSvara, ChantToken, ChantUnit } from '@siksamitra/format';
import { ANU, VIS } from './alphabet.js';
import { norm } from './normalize.js';
import { witnessLine } from './rules/witness.js';

/** Which trigger a substituted letter came from. */
const NASALS: ReadonlySet<string> = new Set(['ṅ', 'ñ', 'ṇ', 'n', 'm']);
const SIBILANTS: ReadonlySet<string> = new Set(['ś', 'ṣ', 's', 'r']);

const undoChange = (u: ChantUnit): string => {
  if (u.change !== true) return u.c;
  if (NASALS.has(u.c)) return ANU;
  if (SIBILANTS.has(u.c)) return VIS;
  return u.c;
};

export interface InvertedSource {
  /** The pre-sandhi letters, one string per displayed line. */
  lines: string[];
  /** The same letters with the accents written back as combining marks. */
  accented: string[];
  /** Whether any accent was found at all — a prose text has none, and giving
   *  it an `accented` layer would claim a witness that does not exist. */
  accents: number;
}

/** Reconstruct a verse's source from its tokens. */
export function invertVerse(tokens: readonly ChantToken[]): InvertedSource {
  const lines: string[] = [];
  const accented: string[] = [];
  let plain = '';
  let witness: { c: string; svara?: ChantSvara }[] = [];
  let accents = 0;

  /*
   * NORMALISED, both of them. A stored source line must be canonical — `norm`
   * idempotent on it — because the whole override addressing scheme is offsets
   * into it (see `rebase.ts` in `@siksamitra/edit`). Returning the raw
   * reconstruction instead meant the first no-op edit re-normalised the line,
   * every offset after the change moved, and three hand-placed marks were
   * reported lost for an edit that inserted nothing.
   */
  const flush = (): void => {
    if (plain.trim() === '') return;
    lines.push(norm(plain));
    accented.push(norm(witnessLine(witness)));
    plain = '';
    witness = [];
  };
  const put = (s: string): void => {
    plain += s;
    witness.push({ c: s });
  };

  for (const t of tokens) {
    if (t.t === 'syl') {
      for (const u of t.units) {
        const c = undoChange(u);
        plain += c;
        if (u.svara === undefined) witness.push({ c });
        else {
          witness.push({ c, svara: u.svara });
          accents += 1;
        }
      }
    } else if (t.t === 'sp') put(' ');
    else if (t.t === 'br') {
      lines.push(norm(plain));
      accented.push(norm(witnessLine(witness)));
      plain = '';
      witness = [];
    }
    /*
     * NOT PADDED. `lex` splits a part at a structure boundary by itself, so
     * `||3||` lexes as daṇḍa · number · daṇḍa with no help — and the source
     * then reads exactly as the document does. Padding it was what put 176
     * verses' worth of spaces into the derived stream that the original never
     * had.
     */
    else if (t.t === 'danda') put(t.s === '॥' ? '||' : '|');
    else if (t.t === 'bar') put('¦');
    else if (t.t === 'num') put(t.s);
  }
  flush();

  return { lines, accented, accents };
}
