import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { mkdirSync } from 'node:fs';
import puppeteer from 'puppeteer-core';
import { browserPath } from '../_browser.mjs';
const DIR='tools/spike-lexical';
const TYPES={'.html':'text/html','.js':'text/javascript','.woff2':'font/woff2'};
const server=createServer(async(req,res)=>{const n=req.url==='/'?'/index.html':req.url;
  try{const b=await readFile(join(DIR,n.replace(/^\//,'')));res.writeHead(200,{'content-type':TYPES[extname(n)]??'text/plain'});res.end(b);}catch{res.writeHead(404);res.end('no');}});
await new Promise(r=>server.listen(5399,r));
const b=await puppeteer.launch({executablePath: browserPath(),headless:'shell',args:['--no-sandbox']});
const p=await b.newPage();
await p.setViewport({width:900,height:220,deviceScaleFactor:3});
await p.goto('http://localhost:5399/',{waitUntil:'networkidle0'});
await p.waitForFunction(()=>window.spike!==undefined);
await p.evaluate(()=>document.fonts.ready);
await new Promise(r=>setTimeout(r,400));
mkdirSync('artifacts/spike',{recursive:true});
await p.screenshot({path:'artifacts/spike/lexical.png',clip:{x:0,y:0,width:900,height:180}});
console.log('artifacts/spike/lexical.png');
await b.close(); server.close();
