#!/usr/bin/env node
/**
 * Vendor the icons, and generate the module the app imports.
 *
 * WHY GENERATED RATHER THAN LOADED. The program has to work with no network,
 * install as one file, and render identically on three operating systems — so
 * an icon font from a CDN, or a runtime `fetch` of an SVG, is not available to
 * it. The set is copied into `assets/icons` (so the licence obligation is
 * visible and the source is auditable) and inlined into one TypeScript module
 * (so the bundle carries it and there is nothing to load).
 *
 * The same pattern as `tools/fonts` — fetch once, vendor, generate, and a
 * `--check` mode a gate can run so a missing or edited icon fails the build
 * rather than showing an empty square in the ribbon.
 *
 *   node tools/icons/gen.mjs           # vendor + generate
 *   node tools/icons/gen.mjs --check   # fail if the generated module is stale
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CAPTION, MARK, SYMBOL } from './manifest.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const SET = join(ROOT, 'node_modules', '@material-symbols', 'svg-400', 'rounded');
const OUT_SVG = join(ROOT, 'assets', 'icons');
const OUT_TS = join(ROOT, 'apps', 'web', 'src', 'ui', 'icons.generated.ts');
const check = process.argv.includes('--check');

/** The `d` attributes of a Material Symbols file, with its own view box. */
function symbol(file) {
  const svg = readFileSync(join(SET, `${file}.svg`), 'utf8');
  const box = /viewBox="([^"]+)"/.exec(svg);
  if (box === null) throw new Error(`${file}: no viewBox`);
  const paths = [...svg.matchAll(/<path\s+d="([^"]+)"\s*\/?>/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`${file}: no paths`);
  return {
    viewBox: box[1],
    /* `currentColor` and no stroke: Material Symbols are filled outlines, so
       they take the text colour of the button they sit in and need no theming
       of their own. */
    body: paths.map((d) => `<path d="${d}"/>`).join(''),
  };
}

const icons = {};
const missing = [];
for (const [name, file] of Object.entries(SYMBOL)) {
  try {
    icons[name] = symbol(file);
  } catch (e) {
    missing.push(`${name} → ${file}.svg (${e.message})`);
  }
}
for (const [name, body] of Object.entries(MARK)) icons[name] = { viewBox: '0 0 24 24', body };
for (const [name, body] of Object.entries(CAPTION)) icons[name] = { viewBox: '0 0 10 10', body };

if (missing.length > 0) {
  console.error(`\n  ${missing.length} icon(s) not in the set:\n`);
  for (const m of missing) console.error(`    ${m}`);
  const near = readdirSync(SET).filter((f) => f.endsWith('.svg') && !f.includes('-fill'));
  console.error(`\n  ${near.length} names available in ${SET}\n`);
  process.exit(1);
}

const names = Object.keys(icons).sort();
const ts = `/* GENERATED by tools/icons/gen.mjs. Do not edit.
 *
 * ${Object.keys(SYMBOL).length} from Material Symbols Rounded 400 (Apache-2.0),
 * ${Object.keys(MARK).length} of our own marking notation, and
 * ${Object.keys(CAPTION).length} window caption glyphs.
 *
 * Inlined rather than loaded: the program runs with no network and installs as
 * one file. See tools/icons/manifest.mjs for what each name means and why.
 */

export interface IconGlyph {
  readonly viewBox: string;
  readonly body: string;
}

export const ICONS = {
${names.map((n) => `  '${n}': ${JSON.stringify(icons[n])},`).join('\n')}
} as const satisfies Record<string, IconGlyph>;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconName[];
`;

if (check) {
  const was = readFileSync(OUT_TS, 'utf8');
  if (was !== ts) {
    console.error('\n  ICONS STALE — run `npm run icons` and commit the result\n');
    process.exit(1);
  }
  console.log(`  ICONS ok — ${names.length} icons, generated module matches the manifest`);
  process.exit(0);
}

mkdirSync(OUT_SVG, { recursive: true });
mkdirSync(dirname(OUT_TS), { recursive: true });
/* The vendored source, one file per icon, so the licence applies to something
   visible and the generated module can be checked against it. */
for (const [name, file] of Object.entries(SYMBOL)) {
  writeFileSync(join(OUT_SVG, `${name}.svg`), readFileSync(join(SET, `${file}.svg`)));
}
for (const [name, glyph] of Object.entries({ ...MARK, ...CAPTION })) {
  const box = MARK[name] === undefined ? '0 0 10 10' : '0 0 24 24';
  writeFileSync(
    join(OUT_SVG, `${name}.svg`),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box}">${glyph}</svg>\n`,
  );
}
writeFileSync(OUT_TS, ts);
writeFileSync(
  join(OUT_SVG, 'LICENSES.md'),
  [
    '# Icons',
    '',
    'Generated by `tools/icons/gen.mjs`. Do not edit by hand.',
    '',
    `- **Material Symbols Rounded 400** — ${Object.keys(SYMBOL).length} icons,`,
    '  Apache License 2.0, © Google. See `node_modules/@material-symbols/svg-400/LICENSE`',
    '  and https://github.com/google/material-design-icons.',
    `- **Marking notation** — ${Object.keys(MARK).length} icons, ours: the holding box in`,
    '  its two stroke weights, and the marks toggle. Same licence as this program.',
    `- **Window caption glyphs** — ${Object.keys(CAPTION).length} icons, ours: drawn to the`,
    "  platform's own 10-unit grid so the window matches its neighbours.",
    '',
  ].join('\n'),
);
console.log(`\n  ${names.length} icons → assets/icons/ and apps/web/src/ui/icons.generated.ts`);
console.log(`    ${Object.keys(SYMBOL).length} Material Symbols · ${Object.keys(MARK).length} marking · ${Object.keys(CAPTION).length} caption\n`);
