/**
 * Tamil — a script module.
 *
 * Tamil Sanskrit, printed the way it is printed.
 *
 * Native Tamil orthography has one letter per stop position — `ப` stands for
 * pa, pha, ba and bha alike — so Sanskrit in Tamil script marks the series with
 * SUPERSCRIPT DIGITS. It is the convention of Ramakrishna Math, Giri and most
 * stotra publishing, and Telugu and Kannada Sanskrit use the same device:
 *
 *     க ka  க² kha  க³ ga  க⁴ gha
 *     த ta  த² tha  த³ da  த⁴ dha
 *     ப pa  ப² pha  ப³ ba  ப⁴ bha
 *
 * The digit is written at the END of the akṣara — `கீ³தா`, not
 * `க³ீதா` — which is what `qualifiers` is for.
 *
 * With the series marked, Tamil is no longer ambiguous: over the corpus it
 * collides on 30 syllables, exactly as Devanāgarī and Telugu do, and every one
 * of those is the virāma tick rather than a letter. So it is `reversible` and
 * `verified` like them.
 *
 * The eleven shipped documents used none of it and collided 215 ways — `ba`,
 * `bha`, `pa` and `pha` all bare `ப`, 24, 140, 302 and 7 times. What they
 * carry is recorded in `corpus/transliteration-reference.json`.
 *
 * GENERATED by tools/gen-script-modules.mjs. Do not edit by hand.
 */

import type { ScriptModule } from '../module.js';

export const TAM: ScriptModule = {
  id: "tam",
  name: "Tamil",
  kind: "abugida",
  reversible: true,
  verified: true,
  qualifiers: "²³⁴",
  virama: "்",
  pranava: "ௐ",
  blocks: [[0x0b80, 0x0bff]],
  letters: {
  "a": "அ",
  "ā": "ஆ",
  "i": "இ",
  "ī": "ஈ",
  "u": "உ",
  "ū": "ஊ",
  "ṛ": null,
  "ṝ": null,
  "ḷ": null,
  "ḹ": null,
  "e": "ஏ",
  "ai": "ஐ",
  "o": "ஓ",
  "au": "ஔ",
  "k": "க",
  "kh": null,
  "g": null,
  "gh": null,
  "ṅ": "ங",
  "c": "ச",
  "ch": null,
  "j": "ஜ",
  "jh": null,
  "ñ": "ஞ",
  "ṭ": "ட",
  "ṭh": null,
  "ḍ": null,
  "ḍh": null,
  "ṇ": "ண",
  "t": "த",
  "th": null,
  "d": null,
  "dh": null,
  "n": "ந",
  "p": "ப",
  "ph": null,
  "b": null,
  "bh": null,
  "m": "ம",
  "y": "ய",
  "r": "ர",
  "l": "ல",
  "v": "வ",
  "ś": "ஶ",
  "ṣ": "ஷ",
  "s": "ஸ",
  "h": "ஹ",
  "ḻ": "ழ",
  "ṁ": "ஂ",
  "ḥ": "ஃ",
  "'": "ऽ",
  "।": "।",
  "॥": "॥",
  },
  signs: {
  "a": "",
  "ā": "ா",
  "i": "ி",
  "ī": "ீ",
  "u": "ு",
  "ū": "ூ",
  "ṛ": null,
  "ṝ": null,
  "ḷ": null,
  "ḹ": null,
  "e": "ே",
  "ai": "ை",
  "o": "ோ",
  "au": "ௌ",
  },
  /* Sounds Tamil has no character for, and the nearest letter it does have.
     A gap is DATA here, never a named branch in shared code. */
  approximations: {
  "ṛ": "ரு'",
  "ṝ": "ரூ'",
  "ḷ": "லு'",
  "ḹ": "லூ'",
  "kh": "க²",
  "g": "க³",
  "gh": "க⁴",
  "ch": "ச²",
  "jh": "ஜ²",
  "ṭh": "ட²",
  "ḍ": "ட³",
  "ḍh": "ட⁴",
  "th": "த²",
  "d": "த³",
  "dh": "த⁴",
  "ph": "ப²",
  "b": "ப³",
  "bh": "ப⁴",
  },
};
