import json
def V(at,spaced,tr=None,**k):
    d={"witness":"w1","at":at,"spaced":spaced}
    if tr: d["translation"]=tr
    d.update(k); return d
U=dict(numbered=False)
ph=[
 V("393",["bhīṣma uvāca"],"Bhīṣma said:",**U),
 V("394-395",["itīdaṁ kīrtanīyasya keśavasya mahā-tmanaḥ ।","nāmnāṁ sahasraṁ divyānām aśeṣeṇa prakīrtitam ॥"],
   "Thus have I recited in full the thousand divine names\nof the great-souled Keśava, whose glory is ever to be sung."),
 V("396-397",["ya idaṁ śṛṇuyān nityaṁ yaś cāpi parikīrtayet ।","nāśubhaṁ prāpnuyāt kiñcit so'mutreha ca mānavaḥ ॥"],
   "He who hears this every day, and he who recites it,\nthat man meets with no evil at all, here or hereafter."),
 V("398-399",["vedānta go brāhmaṇaḥ syāt kṣatriyo vijayī bhavet ।","vaiśyo dhana samṛddhaḥ syāc chūdraḥ sukham avāpnuyāt ॥"],
   "The brāhmaṇa would master the Vedānta, the kṣatriya would be victorious,\nthe vaiśya would prosper in wealth, the śūdra would attain happiness."),
 V("400-401",["dharmā-rthī prāpnuyād dharmam arthā-rthī cārtham āpnuyāt ।","kāmān avāpnuyāt kāmī prajā-rthī prāpnuyāt prajām ॥"],
   "He who seeks dharma attains dharma, he who seeks wealth attains wealth,\nhe who desires attains his desires, he who seeks offspring attains offspring."),
 V("402-403",["bhaktimān yaḥ sado-tthāya śucis tad gata mānasaḥ ।","sahasraṁ vāsudevasya nāmnām etat prakīrtayet ॥"],
   "He who, devoted, rising early and pure, his mind fixed on Him,\nrecites these thousand names of Vāsudeva,"),
 V("404-405",["yaśaḥ prāpnoti vipulaṁ jñāti prādhānyam eva ca ।","acalāṁ śriyam āpnoti śreyaḥ prāpnoty anuttamam ॥"],
   "attains great fame and the first place among his kin,\nattains unwavering prosperity, and attains the highest good."),
 V("406-407",["na bhayaṁ kvacid āpnoti vīryaṁ tejaś ca vindati ।","bhavaty arogo dyutimān bala rūpa guṇā-nvitaḥ ॥"],
   "He never meets with fear, and gains valour and radiance;\nhe becomes free from disease, bright, endowed with strength, beauty and virtue."),
 V("408-409",["rogā-rto mucyate rogād baddho mucyeta bandhanāt ।","bhayān mucyeta bhītas tu mucyetā-panna āpadaḥ ॥"],
   "The sick is freed from sickness, the bound is freed from bondage,\nthe frightened is freed from fear, and one in distress is freed from distress."),
 V("410-411",["durgāṇy atitaraty āśu puruṣaḥ puruṣo-ttamam ।","stuvan nāma sahasreṇa nityaṁ bhakti samanvitaḥ ॥"],
   "That person swiftly crosses over all difficulties\nwho always praises the Supreme Person with the thousand names, full of devotion."),
 V("412-413",["vāsudevā-śrayo martyo vāsudeva parāyaṇaḥ ।","sarva pāpa viśuddhā-tmā yāti brahma sanātanam ॥"],
   "The mortal who takes refuge in Vāsudeva, whose highest goal is Vāsudeva,\nhis self cleansed of all sin, attains the eternal Brahman."),
 V("414-415",["na vāsudeva bhaktānām aśubhaṁ vidyate kvacit ।","janma mṛtyu jarā vyādhi bhayaṁ naivo-pajāyate ॥"],
   "For the devotees of Vāsudeva there is never any evil;\nthe fear of birth, death, old age and disease never arises."),
 V("416-417",["imaṁ stavam adhīyānaḥ śraddhā bhakti samanvitaḥ ।","yujyetā-tma sukha kṣānti śrī dhṛti smṛti kīrtibhiḥ ॥"],
   "He who recites this hymn with faith and devotion\nis joined with joy of the soul, forbearance, prosperity, steadiness, memory and fame."),
 V("418-419",["na krodho na ca mātsaryaṁ na lobho nāśubhā matiḥ ।","bhavanti kṛta puṇyānāṁ bhaktānāṁ puruṣo-ttame ॥"],
   "Neither anger, nor jealousy, nor greed, nor evil thought\narise in the virtuous who are devoted to the Supreme Person."),
 V("420-421",["dyauḥ sacandrā-rka nakṣatrā khaṁ diśo bhūr maho-dadhiḥ ।","vāsudevasya vīryeṇa vidhṛtāni mahā-tmanaḥ ॥"],
   "Heaven with the moon, the sun and the stars, the sky, the quarters, the earth and the great ocean\nare upheld by the might of the great-souled Vāsudeva."),
 V("422-423",["sasurā-sura gandharvaṁ sayakṣo-raga rākṣasam ।","jagad vaśe vartate-daṁ kṛṣṇasya sacarā-caram ॥"],
   "This universe, with gods, demons and gandharvas, with yakṣas, serpents and rākṣasas,\nmoving and unmoving, abides under the sway of Kṛṣṇa."),
 V("424-425",["indriyāṇi mano buddhiḥ sattvaṁ tejo balaṁ dhṛtiḥ ।","vāsudevā-tmakāny āhuḥ kṣetraṁ kṣetrajña eva ca ॥"],
   "The senses, the mind, the intellect, sattva, radiance, strength and steadiness,\nthe field and the knower of the field, are said to have Vāsudeva for their self."),
 V("426-427",["sarvā-gamānām ācāraḥ prathamaṁ parikalpyate ।","ācāra prabhavo dharmo dharmasya prabhur acyutaḥ ॥"],
   "Of all the scriptures, right conduct is held to come first;\ndharma springs from right conduct, and the Lord of dharma is Acyuta."),
 V("428-429",["ṛṣayaḥ pitaro devā mahā bhūtāni dhātavaḥ ।","jaṅgamā-jaṅgamaṁ cedaṁ jagan nārāyaṇo-dbhavam ॥"],
   "The seers, the ancestors, the gods, the great elements and the constituents of the body,\nthis whole world of the moving and the unmoving, has arisen from Nārāyaṇa."),
 V("430-431",["yogo jñānaṁ tathā sāṅkhyaṁ vidyāḥ śilpā-di karma ca ।","vedāḥ śāstrāṇi vijñānam etat sarvaṁ janārdanāt ॥"],
   "Yoga, knowledge and likewise Sāṅkhya, the sciences, the arts and every craft,\nthe Vedas, the scriptures and all learning, all of this comes from Janārdana."),
 V("432-433",["eko viṣṇur mahad bhūtaṁ pṛthag bhūtāny anekaśaḥ ।","trīṁl lokān vyāpya bhūtā-tmā bhuṅkte viśva bhug avyayaḥ ॥"],
   "Viṣṇu, the one great Being, pervades the many separate beings and the three worlds;\nthe Self of all beings, the imperishable enjoyer of the universe, enjoys them all."),
 V("434-435",["imaṁ stavaṁ bhagavato viṣṇor vyāsena kīrtitam ।","paṭhed ya icchet puruṣaḥ śreyaḥ prāptuṁ sukhāni ca ॥"],
   "This hymn to the Blessed Viṣṇu, proclaimed by Vyāsa,\nshould be recited by the person who wishes to attain the highest good and happiness."),
 V("436-437",["viśve-śvaram ajaṁ devaṁ jagataḥ prabhum avyayam ।","bhajanti ye puṣkarā-kṣaṁ na te yānti parābhavam ॥"],
   "Those who worship the lotus-eyed, the Lord of the universe, the unborn God,\nthe imperishable master of the world, never meet with defeat."),
 V("438",["na te yānti parābhavam oṁ nama iti ॥"],**U),
 V("439",["arjuna uvāca"],"Arjuna said:",**U),
 V("440-441",["padma patra viśālā-kṣa padma nābha surottama ।","bhaktānām anuraktānāṁ trātā bhava janārdana ॥"],
   "O you whose eyes are large as lotus petals, from whose navel the lotus springs, best of the gods,\nbe the protector of your loving devotees, O Janārdana."),
 V("442",["śrī bhagavān uvāca"],"The Blessed Lord said:",**U),
 V("443-444",["yo māṁ nāma sahasreṇa stotum icchati pāṇḍava ।","soha'm ekena ślokena stuta eva na saṁśayaḥ ॥"],
   "He who wishes to praise me with the thousand names, O son of Pāṇḍu,\nby him I am praised even with a single verse, there is no doubt."),
 V("445",["stuta eva na saṁśaya oṁ nama iti ॥"],**U),
 V("446",["vyāsa uvāca"],"Vyāsa said:",**U),
 V("447-448",["vāsanād vāsudevasya vāsitaṁ bhuvana trayam ।","sarva bhūta nivāso'si vāsudeva namo'stu te ॥"],
   "Because Vāsudeva dwells in them, the three worlds are his dwelling;\nyou are the abode of all beings, O Vāsudeva, salutation to you."),
 V("449",["śrī vāsudeva namo'stu ta oṁ nama iti ॥"],**U),
 V("450",["pārvaty uvāca"],"Pārvatī said:",**U),
 V("451-452",["keno-pāyena laghunā viṣṇor nāma sahasrakam ।","paṭhyate paṇḍitair nityaṁ śrotum icchāmy ahaṁ prabho ॥"],
   "By what easy means do the learned always recite\nthe thousand names of Viṣṇu? This I wish to hear, O Lord."),
 V("453",["īśvara uvāca"],"Īśvara said:",**U),
 V("454-455",["śrī rāma rāma rāmeti rame rāme manorame ।","sahasra nāma tat tulyaṁ rāma nāma varānane ॥"],
   "“Śrī Rāma, Rāma, Rāma” — so I delight in Rāma, O lovely one;\nthe name of Rāma is equal to the thousand names, O fair-faced one."),
 V("456",["śrī rāma nāma varānana oṁ nama iti ॥"],**U),
 V("457",["brahmo-vāca"],"Brahmā said:",**U),
 V("458-461",["namo'stv anantāya sahasra mūrtaye","sahasra pādā-kṣi śiroru bāhave ।","sahasra nāmne puruṣāya śāśvate","sahasra koṭi yuga dhāriṇe namaḥ ॥"],
   "Salutation to the Infinite, of a thousand forms,\nof a thousand feet, eyes, heads, thighs and arms,\nto the eternal Person of a thousand names,\nwho upholds a thousand crores of ages, salutation."),
 V("462",["sahasra koṭi yuga dhāriṇe nama oṁ nama iti ॥"],**U),
 V("464-465",["oṁ tat sad iti śrī mahābhārate śatasāhasryāṁ saṁhitāyāṁ vaiyāsikyām ānuśāsanike","parvaṇi bhīṣma yudhiṣṭhira saṁvāde śrī viṣṇor divya sahasra nāma stotram ॥"],
   "Oṁ, that is the Real: thus, in the Mahābhārata of a hundred thousand verses, the compilation of Vyāsa, in the book of instruction,\nin the dialogue of Bhīṣma and Yudhiṣṭhira, the hymn of the thousand divine names of Śrī Viṣṇu.",**U),
 V("467",["sañjaya uvāca"],"Sañjaya said:",**U),
 V("468-469",["yatra yoge-śvaraḥ kṛṣṇo yatra pārtho dhanur dharaḥ ।","tatra śrīr vijayo bhūtir dhruvā nītir matir mama ॥"],
   "Wherever there is Kṛṣṇa, the Lord of yoga, wherever there is Arjuna, the bearer of the bow,\nthere are fortune, victory, prosperity and sure justice; such is my conviction.",note="bhagavad gītā 18.78"),
 V("470",["śrī bhagavān uvāca"],"The Blessed Lord said:",**U),
 V("471-472",["ananyāś cintayanto māṁ ye janāḥ paryupāsate ।","teṣāṁ nityā-bhiyuktānāṁ yoga kṣemaṁ vahāmy aham ॥"],
   "Those people who, thinking of me alone, worship me in every way,\nto them, ever united with me, I bring what they lack and preserve what they have.",note="bhagavad gītā 9.22"),
 V("473-474",["paritrāṇāya sādhūnāṁ vināśāya ca duṣkṛtām ।","dharma saṁsthāpanā-rthāya sambhavāmi yuge yuge ॥"],
   "For the protection of the good, for the destruction of the wicked,\nand for the establishment of dharma, I come into being age after age.",note="bhagavad gītā 4.8"),
 V("475-476",["ārtā viṣaṇṇāḥ śithilāś ca bhītā ghoreṣu ca vyādhiṣu vartamānāḥ ।","saṅkīrtya nārāyaṇa śabda mātraṁ vimukta duḥkhāḥ sukhino bhavanti ॥"],
   "The afflicted, the dejected, the weak and the frightened, and those in the grip of terrible diseases,\nby merely uttering the word “Nārāyaṇa” are freed from sorrow and become happy.",note="(upajāti chandaḥ)"),
 V("478-479",["kāyena vācā manase-ndriyair vā buddhyā-tmanā vā prakṛteḥ svabhāvāt ।","karomi yad yat sakalaṁ parasmai nārāyaṇāye-ti samarpayāmi ॥"],
   "Whatever I do with my body, speech, mind or senses, with my intellect or my self, or from the bent of my nature,\nall of it I offer to the Supreme, saying “To Nārāyaṇa”."),
 V("481-482",["iti śrī viṣṇor divya sahasra nāma stotraṁ sampūrṇam ।","oṁ tat sat ॥"],
   "Thus ends the hymn of the thousand divine names of Śrī Viṣṇu.\nOṁ, that is the Real.",**U),
]
doc={"title":"śrī viṣṇu sahasranāma stotram","subtitle":"mahābhārata","locus":"mahābhārata, anuśāsana parva 149","source":"smarta",
 "sections":[{"title":"phalaśrutiḥ","verses":ph}]}
json.dump(doc,open('b3.json','w',encoding='utf-8'),ensure_ascii=False)
print(len(ph))
