# -*- coding: utf-8 -*-
"""Emit shared/src/sankalpa-coord-marks.ts — śikṣā marks (holdings + anusvāra +
visarga; no svara) for the server-computed pañcāṅga coordinate phrases, each
marked on its FULL ASSEMBLED locative form, keyed by the normalised IAST."""
import json, os, re
import gen_marks
from gen_marks import mark, norm
from tokens import compact, line_tokens

# A coordinate phrase is a PIECE OF A LINE (`… śukla-pakṣe ekādaśyāṃ tithau`),
# so the never-box-a-line-initial-cluster rule must not fire while marking one
# on its own — the composer applies it to whichever piece opens the line.
gen_marks.RULES['no_initial_box'] = False

OUT_TS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "..", "shared", "src", "sankalpa-coord-marks.ts")

SAMVATSARA = [
 'Prabhava','Vibhava','Śukla','Pramoda','Prajāpati','Āṅgirasa','Śrīmukha','Bhāva','Yuva',
 'Dhātṛ','Īśvara','Bahudhānya','Pramāthī','Vikrama','Vṛṣa','Citrabhānu','Svabhānu','Tāraṇa',
 'Pārthiva','Vyaya','Sarvajit','Sarvadhārī','Virodhī','Vikṛti','Khara','Nandana','Vijaya',
 'Jaya','Manmatha','Durmukha','Hevilambi','Vilambi','Vikārī','Śārvarī','Plava','Śubhakṛt',
 'Śobhakṛt','Krodhī','Viśvāvasu','Parābhava','Plavaṅga','Kīlaka','Saumya','Sādhāraṇa','Virodhakṛt',
 'Paridhāvī','Pramādī','Ānanda','Rākṣasa','Nala','Piṅgala','Kālayukta','Siddhārthī','Raudra',
 'Durmati','Dundubhi','Rudhirodgārī','Raktākṣī','Krodhana','Akṣaya',
]
AYANA = ['uttarāyaṇe','dakṣiṇāyane']
RITU = ['vasanta','grīṣma','varṣā','śarad','hemanta','śiśira']
MASA = ['caitra','vaiśākha','jyeṣṭha','āṣāḍha','śrāvaṇa','bhādrapada',
        'āśvina','kārtika','mārgaśīrṣa','pauṣa','māgha','phālguna']
PAKSHA = ['kṛṣṇa-pakṣe','śukla-pakṣe']
TITHI_LOC = ['pratipadi','dvitīyāyāṃ','tṛtīyāyāṃ','caturthyāṃ','pañcamyāṃ','ṣaṣṭhyāṃ',
 'saptamyāṃ','aṣṭamyāṃ','navamyāṃ','daśamyāṃ','ekādaśyāṃ','dvādaśyāṃ','trayodaśyāṃ',
 'caturdaśyāṃ','pūrṇimāyāṃ','amāvāsyāyāṃ']
VARA = ['bhānu','indu','bhauma','saumya','guru','bhṛgu','sthira']
NAKSHATRA = ['Aśvinī','Bharaṇī','Kṛttikā','Rohiṇī','Mṛgaśirā','Ārdrā','Punarvasu','Puṣya',
 'Āśleṣā','Maghā','Pūrva Phālgunī','Uttara Phālgunī','Hasta','Citrā','Svātī','Viśākhā',
 'Anurādhā','Jyeṣṭhā','Mūla','Pūrva Āṣāḍhā','Uttara Āṣāḍhā','Śravaṇa','Dhaniṣṭhā','Śatabhiṣā',
 'Pūrva Bhādrapadā','Uttara Bhādrapadā','Revatī','Abhijit']
YOGA = ['Viṣkambha','Prīti','Āyuṣmān','Saubhāgya','Śobhana','Atigaṇḍa','Sukarmā','Dhṛti','Śūla',
 'Gaṇḍa','Vṛddhi','Dhruva','Vyāghāta','Harṣaṇa','Vajra','Siddhi','Vyatīpāta','Varīyān','Parigha',
 'Śiva','Siddha','Sādhya','Śubha','Śukla','Brahma','Indra','Vaidhṛti']
KARANA = ['Bava','Bālava','Kaulava','Taitila','Gara','Vaṇija','Viṣṭi','Śakuni','Catuṣpāda',
 'Nāga','Kiṃstughna']

def build_phrases():
    ph = []
    for n in SAMVATSARA: ph.append(f"{n} nāma saṃvatsare")
    ph += AYANA
    for r in RITU: ph.append(f"{r}-ṛtau")
    for m in MASA:
        ph.append(f"{m}-māse")
        ph.append(f"adhika-{m}-māse")
    ph += PAKSHA
    for t in TITHI_LOC: ph.append(f"{t} tithau")
    for v in VARA: ph.append(f"{v}-vāsare")
    for x in NAKSHATRA: ph.append(f"{x}-nakṣatre")
    for x in YOGA: ph.append(f"{x}-yoge")
    for x in KARANA: ph.append(f"{x}-karaṇe")
    return ph

def emit():
    phrases = build_phrases()
    data = {}
    for p in phrases:
        k = norm(p)
        if k in data: continue
        data[k] = line_tokens(p)
    lines = [
      "// AUTO-GENERATED by tools/chant/coords.py — do not edit by hand.",
      "// Śikṣā marks (holdings + anusvāra + visarga; NO svara) for the server-",
      "// computed pañcāṅga coordinate phrases (saṃvatsara / ayana / ṛtu / māsa /",
      "// pakṣa / tithi / vāra / nakṣatra / yoga / karaṇa), each marked on its full",
      "// assembled locative form. Keyed by the normalised IAST (lower-case, ṃ→ṁ,",
      "// hyphens→spaces, collapsed) so the coordinate builder can attach marks by",
      "// look-up. Same token shape the chant reader consumes (shared/src/chant.ts).",
      "//",
      "// SERVER-ONLY: reached through the \"@vedaunion/shared/sankalpa-coords\"",
      "// subpath, never re-exported from the barrel, so this table does not land",
      "// in the browser bundle — the server ships only the day's ten phrases.",
      "import type { ChantToken } from './chant.js';",
      "",
      "export const SANKALPA_COORD_MARKS: Record<string, ChantToken[]> = {",
    ]
    for k in data:
        lines.append(f"  {json.dumps(k, ensure_ascii=False)}: {compact(data[k])},")
    lines += ["};", ""]
    open(OUT_TS,'w',encoding='utf-8').write("\n".join(lines))
    print(f"wrote {OUT_TS} with {len(data)} coord phrase mark-arrays")
    # spot-check a few
    for probe in ['ekādaśyāṃ tithau','Rohiṇī-nakṣatre','grīṣma-ṛtau',
                  'Viśvāvasu nāma saṃvatsare','adhika-jyeṣṭha-māse','Kiṃstughna-karaṇe']:
        toks = mark(probe)
        r = []
        for tk in toks:
            if tk['t']=='syl':
                r.append(''.join('['+u['c']+('^'+u['hold'][0] if u.get('hold') else '')+
                          ('*' if u.get('change') else '')+('~'+u['sup'] if u.get('sup') else '')+']'
                          for u in tk['units']))
            elif tk['t']=='sp': r.append('/')
            else: r.append(tk['iast'])
        print(f"  {norm(probe):32s} -> {' '.join(r)}")

if __name__=='__main__':
    emit()
