# -*- coding: utf-8 -*-
"""
Per-word grammar for `puja-vidhi.json` (AUTHORING-CHANTS §0.2 / §4).

Keyed by the **surface** a word actually takes in the marked token stream — i.e.
AFTER the anusvāra/visarga transformations `gen_marks` derives (so `devānāṁ`
before `g-` is keyed `devānāṅ`, `guruḥ` before `b-` is keyed `gurur`, …). Run
`gen_puja.py --surfaces` to re-list them; `gen_puja.py` fails loudly if any
surface has no entry, so grammar can never drift out of alignment with the
tokens.

`forms{deva,tel,tam}` are DERIVED from the headword with `indic_transliteration`
— never hand-typed. The dictionary link the reader builds uses the IAST
`lemma` / `root` (ambuda.org Monier-Williams), so every lemma here is an MW
headword (a root for tiṅanta, the prātipadika otherwise).
"""
from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate


def _forms(head):
    if head in ("oṁ", "oṃ", "om"):
        return {"deva": "ॐ", "tel": "ఓం", "tam": "ௐ"}
    b = head.replace("ṁ", "ṃ")
    return {"deva": transliterate(b, sanscript.IAST, sanscript.DEVANAGARI),
            "tel": transliterate(b, sanscript.IAST, sanscript.TELUGU),
            "tam": transliterate(b, sanscript.IAST, sanscript.TAMIL)}


def sub(lemma, meaning, gender=None, vib=None, vac=None, stem=None, note=None):
    g = {"lemma": lemma, "type": "subanta", "meaning": meaning}
    if gender:
        g["gender"] = gender
    if vib:
        g["vibhakti"] = vib
    if vac:
        g["vacana"] = vac
    if stem:
        g["stem"] = stem
    if note:
        g["note"] = note
    g["forms"] = _forms(lemma)
    return g


def tin(root, meaning, gana=None, lakara=None, pur=None, vac=None, note=None):
    g = {"lemma": root, "type": "tinanta", "meaning": meaning, "root": root}
    if gana:
        g["gana"] = gana
    if lakara:
        g["lakara"] = lakara
    if pur:
        g["purusha"] = pur
    if vac:
        g["vacana"] = vac
    if note:
        g["note"] = note
    g["forms"] = _forms(root)
    return g


def _ind(t, lemma, meaning, note=None):
    g = {"lemma": lemma, "type": t, "meaning": meaning}
    if note:
        g["note"] = note
    g["forms"] = _forms(lemma)
    return g


def avy(l, m, note=None):
    return _ind("avyaya", l, m, note)


def upa(l, m, note=None):
    return _ind("upasarga", l, m, note)


def oth(l, m, note=None):
    return _ind("other", l, m, note)


ANUS = "the anusvāra assimilates to the following stop (rendered in the change colour)"

# UPASARGA POLICY (AUTHORING-CHANTS §4): an upasarga prefixed to a FINITE verb
# (tiṅanta) always gets its own `upasarga` entry beside the root — the reader
# then shows the preverb and the root as separate rows, each with its own
# Monier-Williams link, and the same word never appears split in one verse and
# folded in another. A preverb lexicalised into a NOMINAL, participial or gerund
# stem (āvāhita, prokta, praṇamya, upavīta, ācamanīya, sannidhi, …) stays inside
# that entry's lemma, with the derivation in `note` — splitting those would
# invent a preverb the reader cannot see as a separate word.
SAM = upa("sam", "together, fully — carrying the action through")
PRATI = upa("prati", "back, again")
AA = upa("ā", "toward, hither")
NI = upa("ni", "down, into — here of presenting an offering")
PRA = upa("pra", "forth, away")
ANU = upa("anu", "after, in the wake of")
VI = upa("vi", "apart, in various ways")
PARI = upa("pari", "around, on all sides")

# --------------------------------------------------------------------------
# shared / repeated words
# --------------------------------------------------------------------------
OM = avy("oṁ", "oṁ — the praṇava, the sacred syllable that opens a recitation")
CA = avy("ca", "and")
NA = avy("na", "not")
TU = avy("tu", "but, indeed")
NAMAS = sub("namas", "salutation, homage", "n", 1, "eka", "consonant stem (-as)")
SAMARPAYAMI = [SAM, tin("ṛ", "I offer, I present", gana="1 (bhvādi)",
                        lakara="laṭ", pur=1, vac="eka",
                        note="sam + √ṛ, causative arpayati 'to hand over, deliver'")]
KURU = tin("kṛ", "make! do!", gana="8 (tanādi)", lakara="loṭ", pur=2, vac="eka")
ASTU = tin("as", "let it be", gana="2 (adādi)", lakara="loṭ", pur=3, vac="eka")
ANANTARAM = avy("anantaram", "immediately after")
TE_DAT = sub("yuṣmad", "to you", None, 4, "eka", "pronominal (yuṣmad)",
             note="enclitic dative te")
DEVA_ACC = "deva — a slot for the name of the deity being worshipped"

GLOSS = {
    # ── praṇava, particles ────────────────────────────────────────────────
    "oṁ": [OM],
    # Taittirīya prints the praṇava's nasal before a sibilant as the *gum*
    # (`ogṁ suvaḥ`, `ogṁ satyam`) — the same praṇava, a recension spelling.
    "om": [OM],   # the praṇava written with the gum (m + candrabindu)
    "ca": [CA],
    "na": [NA],
    "tu": [TU],
    "eva": [avy("eva", "indeed, alone, precisely")],
    "iti": [avy("iti", "thus — marking the end of a quotation or of a text")],
    "vā": [avy("vā", "or")],
    "tatra": [avy("tatra", "there, in that place")],
    "nityam": [avy("nityam", "constantly, always")],
    "sākṣāt": [avy("sākṣāt", "verily, directly, in person")],
    "śrī": [oth("śrī", "revered, holy",
                note="honorific prefixed to the name of the deity")],

    # ── 1 · dīpa-prajvālanam ─────────────────────────────────────────────────────────
    "dīpajyotiḥ": [sub("dīpajyotis", "the light of the lamp", "n", 1, "eka",
                       "consonant stem -jyotis (dīpa + jyotis)",
                       note="visarga retained before p- as upadhmānīya")],
    "dīpajyotir": [sub("dīpajyotis", "the light of the lamp", "n", 1, "eka",
                       "consonant stem -jyotis (dīpa + jyotis)",
                       note="jyotiḥ → jyotir before a voiced sound")],
    "param": [sub("para", "supreme, highest", "n", 1, "eka", "a-stem",
                  note="agrees with brahma; " + ANUS)],
    "brahma": [sub("brahman", "Brahman — the limitless reality", "n", 1, "eka",
                   "consonant stem (-man)")],
    "janārdanaḥ": [sub("janārdana", "Janārdana — a name of Viṣṇu", "m", 1, "eka", "a-stem")],
    "dīpo": [sub("dīpa", "the lamp", "m", 1, "eka", "a-stem",
                 note="dīpaḥ → dīpo before a voiced sound")],
    "me": [sub("asmad", "my, of me", None, 6, "eka", "pronominal (asmad)",
               note="enclitic me")],
    "haratu": [tin("hṛ", "let it take away, let it remove", gana="1 (bhvādi)",
                   lakara="loṭ", pur=3, vac="eka")],
    "pāpan": [sub("pāpa", "wrongdoing and its result", "n", 2, "eka", "a-stem",
                  note=ANUS)],
    "namo'stu": [sub("namas", "salutation, homage", "n", 1, "eka", "consonant stem (-as)",
                     note="namaḥ + astu → namo'stu"), ASTU],
    "te": [TE_DAT],

    # ── 2a · ācamanam ─────────────────────────────────────────────────────
    "acyutāya": [sub("acyuta", "Acyuta — the one who never falls from his own nature",
                     "m", 4, "eka", "a-stem")],
    "anantāya": [sub("ananta", "Ananta — the endless one", "m", 4, "eka", "a-stem")],
    "govindāya": [sub("govinda", "Govinda — a name of Viṣṇu", "m", 4, "eka", "a-stem")],
    "namaḥ": [NAMAS],

    # ── 2b · guru dhyānam ─────────────────────────────────────────────────
    "gurur": [sub("guru", "the guru, the teacher", "m", 1, "eka", "u-stem",
                  note="guruḥ → gurur before a voiced sound")],
    "gurus": [sub("guru", "the guru, the teacher", "m", 1, "eka", "u-stem",
                  note="guruḥ → gurus before the following s-")],
    "brahmā": [sub("brahman", "Brahmā — the creator", "m", 1, "eka",
                   "consonant stem (-man), masculine")],
    "viṣṇur": [sub("viṣṇu", "Viṣṇu", "m", 1, "eka", "u-stem",
                   note="viṣṇuḥ → viṣṇur before a voiced sound")],
    "devo": [sub("deva", "god, the shining one", "m", 1, "eka", "a-stem",
                 note="devaḥ → devo before a voiced sound")],
    "maheśvaraḥ": [sub("maheśvara", "Maheśvara — the great Lord", "m", 1, "eka",
                       "a-stem (mahā + īśvara)")],
    "tasmai": [sub("tad", "to him, to that one", "m", 4, "eka", "pronominal (tad)")],
    "śrīgurave": [sub("śrīguru", "to the revered guru", "m", 4, "eka",
                      "u-stem (śrī + guru)")],

    # ── 2c · vighneśvara dhyānam ──────────────────────────────────────────
    "śuklāmbaradharaṁ": [sub("śuklāmbaradhara", "wearing white garments", "m", 2, "eka",
                             "bahuvrīhi a-stem (śukla + ambara + dhara)")],
    "viṣṇuṁ": [sub("viṣṇu", "Viṣṇu, the all-pervading one", "m", 2, "eka", "u-stem")],
    "śaśivarṇañ": [sub("śaśivarṇa", "moon-hued", "m", 2, "eka",
                       "bahuvrīhi a-stem (śaśin + varṇa)", note=ANUS)],
    "caturbhujam": [sub("caturbhuja", "four-armed", "m", 2, "eka",
                        "bahuvrīhi a-stem (catur + bhuja)")],
    "prasannavadanan": [sub("prasannavadana", "of gracious countenance", "m", 2, "eka",
                            "bahuvrīhi a-stem (prasanna + vadana)", note=ANUS)],
    "dhyāyet": [tin("dhyai", "let one meditate upon", gana="1 (bhvādi)",
                    lakara="liṅ (opt.)", pur=3, vac="eka")],
    "sarvavighnopaśāntaye": [sub("sarvavighnopaśānti",
                                 "for the quieting of every obstacle", "f", 4, "eka",
                                 "i-stem (sarva + vighna + upaśānti)")],

    # ── 2d · prāṇāyāmaḥ ───────────────────────────────────────────────────
    # The seven vyāhṛtis, the Gāyatrī and the śiras — one passage, Taittirīya
    # Āraṇyaka 10.35. The first three vyāhṛtis are the indeclinable-like world
    # names; the last four are ordinary neuter nominatives.
    "bhūḥ": [sub("bhū", "the earth — the first vyāhṛti", "f", 1, "eka",
                 "root noun bhū",
                 note="each vyāhṛti is uttered with its own praṇava")],
    "bhuvaḥ": [sub("bhuvas", "the mid-region — the second vyāhṛti", "n", 1,
                   "eka", "consonant stem (-as)")],
    "suvaḥ": [sub("suvar", "the heavens — the third vyāhṛti", "n", 1, "eka",
                  "consonant stem (-ar / -as)",
                  note="the Taittirīya form, disyllabic")],
    "mahaḥ": [sub("mahas", "the great — the fourth vyāhṛti", "n", 1, "eka",
                  "consonant stem (-as)")],
    "janaḥ": [sub("janas", "the world of beings — the fifth vyāhṛti", "n", 1,
                  "eka", "consonant stem (-as)")],
    "tapaḥ": [sub("tapas", "the world of austerity — the sixth vyāhṛti", "n", 1,
                  "eka", "consonant stem (-as)")],
    "satyam": [sub("satya", "the true — the seventh vyāhṛti", "n", 1, "eka",
                   "a-stem")],
    "tat": [sub("tad", "that", "n", 2, "eka", "pronominal (tad)",
                note="agreeing with bhargaḥ")],
    "savitur": [sub("savitṛ", "of Savitṛ — the impeller, the sun", "m", 6, "eka",
                    "ṛ-stem (savitṛ)",
                    note="savituḥ → savitur before a voiced sound")],
    "vareṇyam": [sub("vareṇya", "adorable, to be chosen", "n", 2, "eka",
                     "a-stem, gerundive of √vṛ", note=ANUS)],
    "bhargo": [sub("bhargas", "brilliance, radiance", "n", 2, "eka",
                   "consonant stem (-as)",
                   note="bhargaḥ → bhargo before a voiced sound")],
    "devasya": [sub("deva", "of the god", "m", 6, "eka", "a-stem")],
    "dhīmahi": [tin("dhī", "may we meditate upon", lakara="liṅ", pur=1,
                    vac="bahu",
                    note="Vedic middle of √dhī, 'to think, to meditate'")],
    "dhiyo": [sub("dhī", "thoughts, the faculties of understanding", "f", 2,
                  "bahu", "ī-stem (dhī)",
                  note="dhiyaḥ → dhiyo before a voiced sound")],
    "pracodayāt": [PRA,
                   tin("cud", "may he impel, may he urge on", gana="10 (curādi)",
                       lakara="liṅ", pur=3, vac="eka",
                       note="pra + √cud, causative codayati 'to set in motion'")],
    "jyotī": [sub("jyotis", "light", "n", 1, "eka", "consonant stem (-is)",
                  note="jyotiḥ → jyotī, the visarga lost with lengthening before r-")],
    "raso'mṛtam": [sub("rasa", "the essence, the sap", "m", 1, "eka", "a-stem",
                       note="rasaḥ → raso before a voiced sound"),
                   sub("amṛta", "the immortal, the deathless", "n", 1, "eka",
                       "a-stem",
                       note="initial a- elided after -o, written with the avagraha; "
                            + ANUS)],
    "bhūr": [sub("bhū", "the earth — the vyāhṛti", "f", 1, "eka", "root noun bhū",
                 note="bhūḥ → bhūr before a voiced sound")],
    "bhuvas": [sub("bhuvas", "the mid-region — the vyāhṛti", "n", 1, "eka",
                   "consonant stem (-as)", note="bhuvaḥ → bhuvas before s-")],
    "suvar": [sub("suvar", "the heavens — the vyāhṛti", "n", 1, "eka",
                  "consonant stem (-ar)",
                  note="suvaḥ → suvar before a voiced sound")],

    # ── 3 · saṅkalpaḥ ─────────────────────────────────────────────────────
    "mamopātta": [sub("asmad", "my, of me", None, 6, "eka", "pronominal (asmad)",
                      note="mama + upātta → mamopātta"),
                  oth("upātta", "incurred, taken on",
                      note="ppp of upa-ā-√dā; prior member of the compound")],
    "samasta": [oth("samasta", "all, entire",
                    note="uninflected prior member of the compound")],
    "duritakṣayadvārā": [sub("dvār", "by way of the removal of all afflictions",
                             "f", 3, "eka",
                             "consonant stem dvār (durita + kṣaya + dvār)",
                             note="instr. sg. -dvārā used adverbially, 'through the door of', 'by means of'")],
    "śrīparameśvara": [oth("parameśvara", "the revered supreme Lord",
                           note="uninflected prior member of śrīparameśvara-prītyartham")],
    "prītyarthan": [sub("prītyartha", "for the sake of the satisfaction (of)", "m", 2, "eka",
                        "a-stem (prīti + artha)",
                        note="adverbial accusative -artham; " + ANUS)],
    "devapūjāṅ": [sub("devapūjā", "the worship of the deity", "f", 2, "eka",
                      "ā-stem (deva + pūjā)", note=ANUS)],
    "kariṣye": [tin("kṛ", "I shall perform", gana="8 (tanādi)",
                    lakara="lṛṭ (future)", pur=1, vac="eka", note="ātmanepada")],

    # ── 4 · āsana pūjā ────────────────────────────────────────────────────
    "pṛthvi": [sub("pṛthivī", "O Earth", "f", 8, "eka", "ī-stem",
                   note="shortened vocative pṛthvi")],
    "tvayā": [sub("yuṣmad", "by you", None, 3, "eka", "pronominal (yuṣmad)")],
    "dhṛtā": [sub("dhṛta", "held, borne, upheld", "f", 1, "eka",
                  "past participle of √dhṛ",
                  note="fem. nom. sg.; with lokāḥ the received text keeps dhṛtā where agreement would give dhṛtāḥ")],
    "lokāḥ": [sub("loka", "the worlds", "m", 1, "bahu", "a-stem")],
    "devi": [sub("devī", "O Goddess", "f", 8, "eka", "ī-stem")],
    "tvaṁ": [sub("yuṣmad", "you", None, 1, "eka", "pronominal (yuṣmad)")],
    "tvañ": [sub("yuṣmad", "you", None, 1, "eka", "pronominal (yuṣmad)", note=ANUS)],
    "viṣṇunā": [sub("viṣṇu", "by Viṣṇu", "m", 3, "eka", "u-stem")],
    "dhāraya": [tin("dhṛ", "hold! bear! support!", gana="1 (bhvādi)",
                    lakara="loṭ", pur=2, vac="eka",
                    note="causative stem dhāraya- 'to cause to hold, to bear'")],
    "mān": [sub("asmad", "me", None, 2, "eka", "pronominal (asmad)", note=ANUS)],
    "pavitraṅ": [sub("pavitra", "pure", "n", 2, "eka", "a-stem",
                     note="predicative with kuru — 'make (it) pure'; " + ANUS)],
    "kuru": [KURU],
    "cāsanam": [CA, sub("āsana", "the seat", "n", 2, "eka", "a-stem",
                        note="ca + āsanam → cāsanam")],

    # ── 5 · ghaṇṭā pūjā ───────────────────────────────────────────────────
    "āgamārthan": [sub("āgamārtha", "for the coming (of)", "m", 2, "eka",
                       "a-stem (āgama + artha)",
                       note="adverbial accusative -artham; " + ANUS)],
    "devānāṅ": [sub("deva", "of the gods", "m", 6, "bahu", "a-stem", note=ANUS)],
    "gamanārthan": [sub("gamanārtha", "for the going away (of)", "m", 2, "eka",
                        "a-stem (gamana + artha)",
                        note="adverbial accusative -artham; " + ANUS)],
    "rakṣasām": [sub("rakṣas", "of the rākṣasas, the destructive forces", "m", 6, "bahu",
                     "consonant stem (-as)",
                     note="MW has both neuter rakṣas 'harm' and masculine rakṣas "
                          "'a Rākṣasa'; the demon is the masculine")],
    "kurve": [tin("kṛ", "I make, I sound", gana="8 (tanādi)",
                  lakara="laṭ", pur=1, vac="eka", note="ātmanepada")],
    "ghaṇṭāravan": [sub("ghaṇṭārava", "the ringing of the bell", "m", 2, "eka",
                        "a-stem (ghaṇṭā + rava)", note=ANUS)],
    "devatāhvānalāñchanam": [sub("devatāhvānalāñchana",
                                 "the mark of the invocation of the deity", "n", 2, "eka",
                                 "a-stem (devatā + āhvāna + lāñchana)",
                                 note="in apposition to ghaṇṭāravam")],

    # ── 6 · kalaśa pūjā ───────────────────────────────────────────────────
    "gaṅge": [sub("gaṅgā", "O Gaṅgā", "f", 8, "eka", "ā-stem")],
    "yamune": [sub("yamunā", "O Yamunā", "f", 8, "eka", "ā-stem")],
    "caiva": [CA, avy("eva", "indeed", note="ca + eva → caiva")],
    "godāvari": [sub("godāvarī", "O Godāvarī", "f", 8, "eka", "ī-stem")],
    "sarasvati": [sub("sarasvatī", "O Sarasvatī", "f", 8, "eka", "ī-stem")],
    "narmade": [sub("narmadā", "O Narmadā", "f", 8, "eka", "ā-stem")],
    "sindhu": [sub("sindhu", "O Sindhu — the Indus", "m", 8, "eka", "u-stem",
                   note="the regular vocative is sindho; the received text keeps "
                        "the bare stem sindhu")],
    "kāveri": [sub("kāverī", "O Kāverī", "f", 8, "eka", "ī-stem")],
    "jale'smin": [sub("jala", "in the water", "n", 7, "eka", "a-stem"),
                  sub("idam", "in this", "n", 7, "eka", "pronominal (idam)",
                      note="jale asmin → jale'smin")],
    "sannidhiṅ": [sub("sannidhi", "presence, nearness", "m", 2, "eka", "i-stem",
                      note="sannidhiṁ kuru — 'be present'; " + ANUS)],

    # ── 7 · ātma pūjā ─────────────────────────────────────────────────────
    "deho": [sub("deha", "the body", "m", 1, "eka", "a-stem",
                 note="dehaḥ → deho before a voiced sound")],
    "devālayaḥ": [sub("devālaya", "the temple, the dwelling of the deity", "m", 1, "eka",
                      "a-stem (deva + ālaya)")],
    "proktaḥ": [sub("prokta", "is called, is said to be", "m", 1, "eka",
                    "past participle of pra-√vac")],
    "jīvo": [sub("jīva", "the jīva — the individual living being", "m", 1, "eka", "a-stem",
                 note="jīvaḥ → jīvo before a voiced sound")],
    "devas": [sub("deva", "the deity", "m", 1, "eka", "a-stem",
                  note="devaḥ → devas before the following s-")],
    "sanātanaḥ": [sub("sanātana", "eternal, from beginningless time", "m", 1, "eka", "a-stem")],
    "tyajed": [tin("tyaj", "let one give up, let one discard", gana="1 (bhvādi)",
                   lakara="liṅ (opt.)", pur=3, vac="eka",
                   note="tyajet → tyajed before a voiced sound")],
    "ajñānanirmālyaṁ": [sub("ajñānanirmālya",
                            "the withered flower-offering that is ignorance", "n", 2, "eka",
                            "a-stem (ajñāna + nirmālya)")],
    "so'ham": [sub("tad", "he, that one", "m", 1, "eka", "pronominal (tad)",
                   note="saḥ + aham → so'ham"),
               sub("asmad", "I", None, 1, "eka", "pronominal (asmad)")],
    "bhāvena": [sub("bhāva", "with the attitude, with the conviction", "m", 3, "eka", "a-stem")],
    "pūjayet": [tin("pūj", "let one worship", gana="10 (curādi)", lakara="liṅ (opt.)",
                    pur=3, vac="eka")],

    # ── upacāra 1 · āvāhanam ──────────────────────────────────────────────
    "asmin": [sub("idam", "in this", "n", 7, "eka", "pronominal (idam)")],
    "bimbe": [sub("bimba", "in the image, in the icon", "n", 7, "eka", "a-stem")],
    "devan": [sub("deva", DEVA_ACC, "m", 2, "eka", "a-stem", note=ANUS)],
    "devam": [sub("deva", DEVA_ACC, "m", 2, "eka", "a-stem",
                  note="before a vowel the word-final -m stays m, never anusvāra")],
    "devaṅ": [sub("deva", "the Lord, the deity", "m", 2, "eka", "a-stem", note=ANUS)],
    "dhyāyāmi": [tin("dhyai", "I meditate upon, I visualise", gana="1 (bhvādi)",
                     lakara="laṭ", pur=1, vac="eka")],
    "āvāhayāmi": [AA, tin("vah", "I invoke, I invite (the deity) in",
                          gana="1 (bhvādi)", lakara="laṭ",
                          pur=1, vac="eka", note="ā + √vah, causative")],

    # ── upacāras 2–16 · the offering formulae ─────────────────────────────
    "samarpayāmi": SAMARPAYAMI,
    "āsanaṁ": [sub("āsana", "a seat", "n", 2, "eka", "a-stem")],
    "pādyaṁ": [sub("pādya", "water for washing the feet", "n", 2, "eka",
                   "a-stem (from pāda 'foot')")],
    "arghyaṁ": [sub("arghya", "water offered in respectful reception", "n", 2, "eka", "a-stem")],
    "ācamanīyaṁ": [sub("ācamanīya", "water for sipping, for inner purification",
                       "n", 2, "eka", "a-stem (gerundive of ā-√cam)")],
    "madhuparkaṁ": [sub("madhuparka", "the honey-mixture offered to an honoured guest",
                        "m", 2, "eka", "a-stem")],
    "snānaṁ": [sub("snāna", "a bath", "n", 2, "eka", "a-stem")],
    "snānānantaram": [oth("snāna", "the bath",
                          note="prior member of snāna-anantaram"), ANANTARAM],
    "vastraṁ": [sub("vastra", "cloth, a garment", "n", 2, "eka", "a-stem")],
    "upavītaṁ": [sub("upavīta", "the sacred thread", "n", 2, "eka",
                     "a-stem (ppp of upa-√vye)")],
    "ābharaṇaṁ": [sub("ābharaṇa", "an ornament", "n", 2, "eka", "a-stem")],
    "gandhān": [sub("gandha", "fragrant substances — sandal paste", "m", 2, "bahu", "a-stem")],
    "dhārayāmi": [tin("dhṛ", "I apply, I place upon", gana="1 (bhvādi)",
                      lakara="laṭ", pur=1, vac="eka",
                      note="causative stem dhāraya- 'to cause to hold, to bear'")],
    "gandhasyopari": [sub("gandha", "of the sandal paste", "m", 6, "eka", "a-stem"),
                      avy("upari", "above, over",
                          note="gandhasya + upari → gandhasyopari")],
    "haridrākuṅkumaṁ": [sub("haridrākuṅkuma", "turmeric and vermilion", "n", 2, "eka",
                            "a-stem (haridrā + kuṅkuma)")],
    "puṣpāṇi": [sub("puṣpa", "flowers", "n", 2, "bahu", "a-stem")],
    "dhūpam": [sub("dhūpa", "incense", "m", 2, "eka", "a-stem")],
    "āghrāpayāmi": [AA, tin("ghrā", "I offer to be smelt",
                            gana="1 (bhvādi)",
                            lakara="laṭ", pur=1, vac="eka", note="ā + √ghrā, causative")],
    "dīpaṁ": [sub("dīpa", "the lamp, the light", "m", 2, "eka", "a-stem")],
    "sandarśayāmi": [SAM, tin("dṛś", "I show, I display",
                              gana="1 (bhvādi)",
                              lakara="laṭ", pur=1, vac="eka",
                              note="sam + √dṛś, causative darśayati 'to show'")],
    "dhūpadīpānantaram": [oth("dhūpadīpa", "incense and lamp",
                              note="prior member of dhūpadīpa-anantaram"), ANANTARAM],
    "prāṇāya": [sub("prāṇa", "to prāṇa — the forward-moving breath", "m", 4, "eka", "a-stem")],
    "apānāya": [sub("apāna", "to apāna — the downward-moving breath", "m", 4, "eka", "a-stem")],
    "vyānāya": [sub("vyāna", "to vyāna — the diffused breath", "m", 4, "eka", "a-stem")],
    "udānāya": [sub("udāna", "to udāna — the upward-moving breath", "m", 4, "eka", "a-stem")],
    "samānāya": [sub("samāna", "to samāna — the equalising breath", "m", 4, "eka", "a-stem")],
    "brahmaṇe": [sub("brahman", "to Brahman", "n", 4, "eka", "consonant stem (-man)")],
    "svāhā": [avy("svāhā", "svāhā — the call with which an oblation is released")],
    "naivedyaṁ": [sub("naivedya", "the food offering", "n", 2, "eka", "a-stem")],
    "nivedayāmi": [NI, tin("vid", "I present, I make (it) known",
                           gana="2 (adādi)", lakara="laṭ",
                           pur=1, vac="eka",
                           note="ni + √vid, causative vedayati 'to make known'")],
    "naivedyānantaram": [oth("naivedya", "the food offering",
                             note="prior member of naivedya-anantaram"), ANANTARAM],
    "tāmbūlaṁ": [sub("tāmbūla", "betel leaf with areca nut", "n", 2, "eka", "a-stem")],
    "karpūranīrājanaṁ": [sub("karpūranīrājana", "the waving of lighted camphor",
                             "n", 2, "eka", "a-stem (karpūra + nīrājana)")],
    "mantrapuṣpāñjaliṁ": [sub("mantrapuṣpāñjali",
                              "a cupped handful of flowers offered with mantras",
                              "m", 2, "eka", "i-stem (mantra + puṣpa + añjali)")],
    "pradakṣiṇanamaskārān": [sub("pradakṣiṇanamaskāra",
                                 "circumambulations and prostrations", "m", 2, "bahu",
                                 "a-stem (pradakṣiṇa + namaskāra)")],

    # ── upacāra 14 · naivedyam ────────────────────────────────────────────
    "satyan": [sub("satya", "the true, the real", "n", 2, "eka", "a-stem",
                   note=ANUS)],
    "tvā": [sub("yuṣmad", "you", None, 2, "eka", "pronominal (yuṣmad)",
                note="enclitic accusative tvā")],
    "ṛtena": [sub("ṛta", "with the ṛta — the cosmic order, the true course of "
                  "things", "n", 3, "eka", "a-stem")],
    "pariṣiñcāmi": [PARI, tin("sic", "I sprinkle around, I encircle with water",
                              gana="6 (tudādi)", lakara="laṭ", pur=1, vac="eka",
                              note="pari + √sic; s → ṣ after the i of pari")],
    # --- the three units closing the gurukulam's naivedya -----------------
    "madhye": [sub("madhya", "in the middle", "n", 7, "eka", "a-stem",
                   note="doubled — madhye madhye, 'between and between'")],
    "udaka": [sub("udaka", "water", "n", None, None, "a-stem",
                  note="first member of udaka-pānīya")],
    "pānīyaṁ": [sub("pānīya", "water for drinking", "n", 2, "eka", "a-stem",
                    note="gerundive of √pā, 'to be drunk'")],
    "uttarāpośanaṁ": [sub("uttarāpośana", "the concluding sip of water", "n", 2,
                          "eka", "a-stem",
                          note="uttara (after) + apośana (the sip taken round "
                               "the food)")],
    "hastau": [sub("hasta", "the two hands", "m", 2, "dvi", "a-stem")],
    "pādau": [sub("pāda", "the two feet", "m", 2, "dvi", "a-stem")],
    "mukhe": [sub("mukha", "at the mouth", "n", 7, "eka", "a-stem")],
    "prakṣālayāmi": [PRA, tin("kṣal", "I wash, I rinse", gana="10 (curādi)",
                              lakara="laṭ", pur=1, vac="eka",
                              note="pra + √kṣal, causative")],
    "śuddhācamanīyaṁ": [sub("śuddha", "pure, clean", "n", 2, "eka", "a-stem"),
                        sub("ācamanīya", "water for sipping", "n", 2, "eka",
                            "a-stem", note="gerundive of ā-√cam")],

    # --- the third guru verse, from VU's Śrī Rudram prastāvanā -------------
    "vande": [tin("vand", "I bow to, I salute", gana="1 (bhvādi)",
                  lakara="laṭ", pur=1, vac="eka")],
    "gurupadadvandvamavāṅmanasagocaram": [
        sub("gurupadadvandva", "the pair of the guru's feet", "n", 2, "eka",
            "a-stem", note="guru + pada + dvandva (a pair)"),
        sub("avāṅmanasagocara", "not within the range of speech or mind", "n",
            2, "eka", "a-stem",
            note="a- + vāc + manas + gocara (range, pasture)")],
    "raktaśuklaprabhāmiśramatarkyan": [
        sub("raktaśuklaprabhāmiśra", "mingled with red and white radiance", "n",
            2, "eka", "a-stem", note="rakta + śukla + prabhā + miśra"),
        sub("atarkya", "inconceivable, beyond reasoning", "n", 2, "eka",
            "a-stem", note="a- + tarkya, gerundive of √tark. " + ANUS)],
    "traipuram": [sub("traipura", "of Tripurā, belonging to the three cities",
                      "n", 2, "eka", "a-stem")],

    # --- the auspicious opening: gaṇānāṁ tvā (TS 2.3.14) and pra ṇo devī
    # --- sarasvatī (TS 1.8.22), as the Veda Union sādhana prints them -------
    # Several surfaces here are two words the recitation runs together; each
    # gets its own entry under the joined surface, in order.
    "gaṇānān": [sub("gaṇa", "of the troops, of the gaṇas", "m", 6, "bahu",
                    "a-stem", note=ANUS)],
    "gaṇapatim": [sub("gaṇapati", "the lord of the gaṇas", "m", 2, "eka",
                      "i-stem",
                      note="the anusvāra is the Vedic nasal, the gum — a "
                           "Taittirīya reading, printed so in both sources and "
                           "authored rather than derived")],
    "havāmahe": [tin("hve", "we call, we summon", gana="1 (bhvādi)",
                     lakara="laṭ", pur=1, vac="bahu", note="ātmanepada")],
    "kaviṅ": [sub("kavi", "the sage, the seer", "m", 2, "eka", "i-stem",
                  note=ANUS)],
    "kavīnāmupamaśravastamam": [
        sub("kavi", "of the sages", "m", 6, "bahu", "i-stem"),
        sub("upamaśravastama", "highest in renown", "m", 2, "eka", "a-stem",
            note="upama (highest) + śravas (fame) + -tama (superlative)")],
    "jyeṣṭharājam": [sub("jyeṣṭharāja", "eldest king", "m", 2, "eka", "a-stem",
                         note="jyeṣṭha + rāja. " + ANUS)],
    "brahmaṇām": [sub("brahman", "of the sacred words", "n", 6, "bahu",
                      "consonant stem (-man)", note=ANUS)],
    "brahmaṇaspata": [sub("brahmaṇaspati", "O lord of the sacred word", "m", 8,
                          "eka", "i-stem",
                          note="brahmaṇaḥ + pati, a fixed Vedic compound; "
                               "vocative")],
    "naś": [sub("asmad", "us", None, 2, "bahu", "pronominal (asmad)",
                note="enclitic naḥ → naś before ś-")],
    "śṛṇvannūtibhis": [
        sub("śṛṇvat", "hearing", "m", 1, "eka",
            "present participle of √śru"),
        sub("ūti", "with helps, with favours", "f", 3, "bahu", "i-stem")],
    "sīda": [tin("sad", "sit!, take your seat", gana="1 (bhvādi)",
                 lakara="loṭ", pur=2, vac="eka")],
    "sādanam": [sub("sādana", "the seat, the place of sitting", "n", 2, "eka",
                    "a-stem")],
    "mahāgaṇapataye": [sub("mahāgaṇapati", "to Mahāgaṇapati", "m", 4, "eka",
                           "i-stem")],
    "pra": [upa("pra", "forth, forward — here with the verb of the next line")],
    "ṇo": [sub("asmad", "to us, for us", None, 4, "bahu",
               "pronominal (asmad)",
               note="enclitic naḥ → no; the n becomes ṇ after the r of pra")],
    "devī": [sub("devī", "the goddess", "f", 1, "eka", "ī-stem")],
    "sarasvatī": [sub("sarasvatī", "Sarasvatī", "f", 1, "eka", "ī-stem")],
    "vājebhir": [sub("vāja", "with strength, with prizes", "m", 3, "bahu",
                     "a-stem", note="Vedic -ebhiḥ for -aiḥ")],
    "vājinīvatī": [sub("vājinīvatī", "abounding in rewards", "f", 1, "eka",
                       "ī-stem")],
    "dhīnāmavitryavatu": [
        sub("dhī", "of thoughts, of the wits", "f", 6, "bahu", "ī-stem"),
        sub("avitrī", "the protectress", "f", 1, "eka", "ī-stem"),
        tin("av", "may she protect, let her favour", gana="1 (bhvādi)",
            lakara="loṭ", pur=3, vac="eka")],
    "vāgdevyai": [sub("vāgdevī", "to the goddess of speech", "f", 4, "eka",
                      "ī-stem", note="vāc + devī")],

    # --- the guru vandanam and Guru śloka II, from the Veda Union sādhana ---
    # `guṁ` and `paṁ` keep their anusvāra because they are bījas — the sādhana's
    # own marked text prints them so, where the ordinary rule would have given
    # guṅ before g- and pam before p-. See gen_marks.BIJA.
    # The gurukulam prints the sandhi'd form `tvartena` (tvā + ṛtena), so it is
    # keyed that way and the two words are given as two entries under it.
    "tvartena": [sub("yuṣmad", "you", None, 2, "eka", "pronominal (yuṣmad)",
                     note="tvā + ṛtena → tvartena"),
                 sub("ṛta", "by the ṛta, by the cosmic order", "n", 3, "eka",
                     "a-stem")],
    "guṁ": [oth("guṁ", "the bīja opening the salutation to the gurus")],
    "paṁ": [oth("paṁ", "the bīja opening the two lines that follow")],
    "gurubhyo": [sub("guru", "to the gurus", "m", 4, "bahu", "u-stem",
                     note="gurubhyaḥ → gurubhyo before a voiced sound")],
    "parama": [sub("parama", "highest, most excellent", "m", None, None, "a-stem",
                   note="first member of parama-guru, printed as a separate word")],
    "parameṣṭhi": [sub("parameṣṭhin", "standing in the highest place", "m", None,
                       None, "consonant stem (-in)",
                       note="first member of parameṣṭhi-guru, printed as a "
                            "separate word")],
    "akhaṇḍamaṇḍalākāraṁ": [sub("akhaṇḍamaṇḍalākāra",
                                "having the form of the unbroken whole", "n", 1,
                                "eka", "a-stem",
                                note="akhaṇḍa (unbroken) + maṇḍala (orb) + ākāra "
                                     "(form); agrees with carācaram")],
    "vyāptaṁ": [sub("vyāpta", "pervaded", "n", 1, "eka",
                    "past participle of vi-√āp")],
    "yena": [sub("yad", "by whom", "m", 3, "eka", "pronominal (yad)")],
    "carācaram": [sub("carācara", "the moving and the unmoving", "n", 1, "eka",
                      "a-stem", note="cara + acara")],
    "tatpadan": [sub("tatpada", "that state, that abode", "n", 2, "eka", "a-stem",
                     note="tat + pada. " + ANUS)],
    "darśitaṁ": [sub("darśita", "shown, revealed", "n", 1, "eka",
                     "causative past participle of √dṛś")],

    "amṛtam": [sub("amṛta", "nectar, the deathless", "n", 1, "eka", "a-stem",
                   note="predicate nominative with astu — 'let it be nectar'")],
    "amṛtopastaraṇam": [sub("amṛtopastaraṇa",
                            "the underlayer of the nectar — the water sipped "
                            "before eating, spread beneath the food", "n", 1,
                            "eka", "a-stem",
                            note="amṛta + upastaraṇa (upa + √stṛ, 'to spread "
                                 "under'); amṛta + upa- → amṛto-")],
    "amṛtāpidhānam": [sub("amṛtāpidhāna",
                          "the covering of the nectar — the water sipped after "
                          "eating, sealing it", "n", 1, "eka", "a-stem",
                          note="amṛta + apidhāna (api + √dhā, 'to cover'); "
                               "amṛta + api- → amṛtāpi-")],
    "asi": [tin("as", "you are", gana="2 (adādi)", lakara="laṭ", pur=2,
                vac="eka")],

    # ── upacāra 11a · the eighteen names ──────────────────────────────────
    "sumukhāya": [sub("sumukha", "to the one of beautiful face", "m", 4, "eka", "a-stem")],
    "ekadantāya": [sub("ekadanta", "to the single-tusked one", "m", 4, "eka", "a-stem")],
    "kapilāya": [sub("kapila", "to the tawny one", "m", 4, "eka", "a-stem")],
    "gajakarṇakāya": [sub("gajakarṇaka", "to the one with elephant ears", "m", 4, "eka",
                          "a-stem (gaja + karṇaka)")],
    "lambodarāya": [sub("lambodara", "to the pendulous-bellied one", "m", 4, "eka",
                        "bahuvrīhi a-stem (lamba + udara)")],
    "vikaṭāya": [sub("vikaṭa", "to the huge and formidable one", "m", 4, "eka", "a-stem")],
    "vighnarājāya": [sub("vighnarāja", "to the lord of obstacles", "m", 4, "eka",
                         "a-stem (vighna + rāja)")],
    "vināyakāya": [sub("vināyaka", "to the foremost leader", "m", 4, "eka", "a-stem")],
    "dhūmraketave": [sub("dhūmraketu", "to the smoke-bannered one", "m", 4, "eka",
                         "u-stem (dhūmra + ketu)")],
    "gaṇādhyakṣāya": [sub("gaṇādhyakṣa", "to the overseer of the gaṇas", "m", 4, "eka",
                          "a-stem (gaṇa + adhyakṣa)")],
    "bhālacandrāya": [sub("bhālacandra", "to the one with the moon on his brow",
                          "m", 4, "eka", "bahuvrīhi a-stem (bhāla + candra)")],
    "gajānanāya": [sub("gajānana", "to the elephant-faced one", "m", 4, "eka",
                       "bahuvrīhi a-stem (gaja + ānana)")],
    "vakratuṇḍāya": [sub("vakratuṇḍa", "to the curved-trunked one", "m", 4, "eka",
                         "bahuvrīhi a-stem (vakra + tuṇḍa)")],
    "śūrpakarṇāya": [sub("śūrpakarṇa", "to the winnowing-basket-eared one", "m", 4, "eka",
                         "bahuvrīhi a-stem (śūrpa + karṇa)")],
    "herambāya": [sub("heramba", "to Heramba", "m", 4, "eka", "a-stem")],
    "skandapūrvajāya": [sub("skandapūrvaja", "to the one born before Skanda", "m", 4, "eka",
                            "a-stem (skanda + pūrvaja)")],
    "siddhivināyakāya": [sub("siddhivināyaka", "to the Vināyaka of accomplishment",
                             "m", 4, "eka", "a-stem (siddhi + vināyaka)")],
    "jñānagaṇapataye": [sub("jñānagaṇapati", "to the Gaṇapati of knowledge", "m", 4, "eka",
                            "i-stem (jñāna + gaṇapati)")],

    # ── upacāra 15 · na tatra sūryo bhāti ─────────────────────────────────
    "sūryo": [sub("sūrya", "the sun", "m", 1, "eka", "a-stem",
                  note="sūryaḥ → sūryo before a voiced sound")],
    "bhāti": [tin("bhā", "shines", gana="2 (adādi)", lakara="laṭ", pur=3, vac="eka")],
    "candratārakaṁ": [sub("candratāraka", "the moon and the stars", "n", 1, "eka",
                          "a-stem (candra + tāraka)")],
    "nemā": [NA, sub("idam", "these", "f", 1, "bahu", "pronominal (idam)",
                     note="na + imāḥ → nemāḥ; agrees with vidyutaḥ")],
    "vidyuto": [sub("vidyut", "lightnings", "f", 1, "bahu", "consonant stem (vi-√dyut)",
                    note="vidyutaḥ → vidyuto before a voiced sound")],
    "bhānti": [tin("bhā", "they shine", gana="2 (adādi)", lakara="laṭ", pur=3, vac="bahu")],
    "kuto'yam": [avy("kutas", "whence? — here 'how much less'"),
                 sub("idam", "this", "m", 1, "eka", "pronominal (idam)",
                     note="kutaḥ + ayam → kuto'yam")],
    "agniḥ": [sub("agni", "fire", "m", 1, "eka", "i-stem")],
    "tam": [sub("tad", "him, that", "m", 2, "eka", "pronominal (tad)")],
    "bhāntam": [sub("bhā", "shining — the one that shines", "m", 2, "eka",
                    "present participle of √bhā (bhānt-)",
                    note="acc. sg. m., agreeing with tam")],
    "anubhāti": [ANU, tin("bhā", "shines after it", gana="2 (adādi)", lakara="laṭ",
                          pur=3, vac="eka", note="anu + √bhā")],
    "sarvaṅ": [sub("sarva", "everything, all", "n", 1, "eka", "pronominal a-stem")],
    "tasya": [sub("tad", "of that, his", None, 6, "eka", "pronominal (tad)")],
    "bhāsā": [sub("bhās", "by the light, by the radiance", "f", 3, "eka",
                  "consonant stem (-as, feminine)")],
    "sarvam": [sub("sarva", "all, the whole of it", "n", 1, "eka", "pronominal a-stem")],
    "idaṁ": [sub("idam", "this", "n", 1, "eka", "pronominal (idam)")],
    "vibhāti": [VI, tin("bhā", "shines forth, shines in many forms", gana="2 (adādi)",
                        lakara="laṭ", pur=3, vac="eka", note="vi + √bhā")],

    # ── upacāra 16 · pradakṣiṇa ───────────────────────────────────────────
    "yāni": [sub("yad", "which, whatever", "n", 1, "bahu", "pronominal (yad)")],
    "kāni": [sub("kim", "whatever", "n", 1, "bahu", "pronominal (kim)",
                 note="yāni kāni ca — 'whatsoever'")],
    "pāpāni": [sub("pāpa", "wrongs, misdeeds", "n", 1, "bahu", "a-stem")],
    "janmāntarakṛtāni": [sub("janmāntarakṛta", "done in another birth", "n", 1, "bahu",
                             "past-participle compound (janman + antara + kṛta)")],
    "tāni": [sub("tad", "those", "n", 1, "bahu", "pronominal (tad)")],
    "praṇaśyanti": [PRA, tin("naś", "they perish, they are destroyed",
                             gana="4 (divādi)", lakara="laṭ", pur=3, vac="bahu",
                             note="pra + √naś")],
    "pradakṣiṇam": [sub("pradakṣiṇa", "circumambulation, keeping the right side toward",
                        "n", 2, "eka", "a-stem", note="adverbial accusative")],
    "pade": [sub("pada", "at (each) step", "n", 7, "eka", "a-stem",
                 note="pade pade — 'at every step'")],

    # ── the stotram ───────────────────────────────────────────────────────
    "nārada": [sub("nārada", "Nārada — the divine seer", "m", 1, "eka", "a-stem")],
    "uvāca": [tin("vac", "said, spoke", gana="2 (adādi)", lakara="liṭ (perfect)",
                  pur=3, vac="eka")],
    "praṇamya": [avy("praṇamya", "having bowed down",
                     note="gerund (lyap) of pra-√nam 'to bow'")],
    "śirasā": [sub("śiras", "with the head", "n", 3, "eka", "consonant stem (-as)")],
    "gaurīputraṁ": [sub("gaurīputra", "the son of Gaurī", "m", 2, "eka",
                        "a-stem (gaurī + putra)")],
    "vināyakam": [sub("vināyaka", "Vināyaka — the foremost leader", "m", 2, "eka", "a-stem")],
    "bhaktāvāsaṁ": [sub("bhaktāvāsa", "the one who dwells in his devotees", "m", 2, "eka",
                        "a-stem (bhakta + āvāsa)")],
    "smaren": [tin("smṛ", "let one remember", gana="1 (bhvādi)", lakara="liṅ (opt.)",
                   pur=3, vac="eka", note="smaret → smaren before n-")],
    "āyuḥkāmārthasiddhaye": [sub("āyuḥkāmārthasiddhi",
                                 "for the attaining of long life, of what one wishes, and of prosperity",
                                 "f", 4, "eka", "i-stem (āyus + kāma + artha + siddhi)")],
    "prathamaṁ": [sub("prathama", "the first", "m", 2, "eka", "a-stem ordinal")],
    "vakratuṇḍañ": [sub("vakratuṇḍa", "Vakratuṇḍa — the curved-trunked one", "m", 2, "eka",
                        "bahuvrīhi a-stem", note=ANUS)],
    "ekadantan": [sub("ekadanta", "Ekadanta — the single-tusked one", "m", 2, "eka",
                      "bahuvrīhi a-stem", note=ANUS)],
    "dvitīyakam": [sub("dvitīyaka", "the second", "m", 2, "eka", "a-stem ordinal")],
    "tṛtīyaṅ": [sub("tṛtīya", "the third", "m", 2, "eka", "a-stem ordinal", note=ANUS)],
    "kṛṣṇapiṅgākṣaṅ": [sub("kṛṣṇapiṅgākṣa", "Kṛṣṇapiṅgākṣa — the dark tawny-eyed one",
                           "m", 2, "eka", "bahuvrīhi a-stem", note=ANUS)],
    "gajavaktrañ": [sub("gajavaktra", "Gajavaktra — the elephant-faced one", "m", 2, "eka",
                        "bahuvrīhi a-stem", note=ANUS)],
    "caturthakam": [sub("caturthaka", "the fourth", "m", 2, "eka", "a-stem ordinal")],
    "lambodaram": [sub("lambodara", "Lambodara — the pendulous-bellied one", "m", 2, "eka",
                       "bahuvrīhi a-stem")],
    "pañcamañ": [sub("pañcama", "the fifth", "m", 2, "eka", "a-stem ordinal", note=ANUS)],
    "ṣaṣṭhaṁ": [sub("ṣaṣṭha", "the sixth", "m", 2, "eka", "a-stem ordinal")],
    "vikaṭam": [sub("vikaṭa", "Vikaṭa — the huge one", "m", 2, "eka", "a-stem")],
    "saptamaṁ": [sub("saptama", "the seventh", "m", 2, "eka", "a-stem ordinal")],
    "vighnarājañ": [sub("vighnarāja", "Vighnarāja — the lord of obstacles", "m", 2, "eka",
                        "a-stem (vighna + rāja)", note=ANUS)],
    "dhūmravarṇan": [sub("dhūmravarṇa", "Dhūmravarṇa — the smoke-hued one", "m", 2, "eka",
                         "bahuvrīhi a-stem", note=ANUS)],
    "tathā'ṣṭamam": [avy("tathā", "likewise, and so"),
                     sub("aṣṭama", "the eighth", "m", 2, "eka", "a-stem ordinal",
                         note="tathā + aṣṭamam; the source writes the junction with an avagraha")],
    "navamam": [sub("navama", "the ninth", "m", 2, "eka", "a-stem ordinal")],
    "bhālacandrañ": [sub("bhālacandra", "Bhālacandra — the one with the moon on his brow",
                         "m", 2, "eka", "bahuvrīhi a-stem", note=ANUS)],
    "daśaman": [sub("daśama", "the tenth", "m", 2, "eka", "a-stem ordinal", note=ANUS)],
    "ekādaśaṅ": [sub("ekādaśa", "the eleventh", "m", 2, "eka", "a-stem ordinal", note=ANUS)],
    "gaṇapatin": [sub("gaṇapati", "Gaṇapati — the lord of the gaṇas", "m", 2, "eka",
                      "i-stem", note=ANUS)],
    "dvādaśan": [sub("dvādaśa", "the twelfth", "m", 2, "eka", "a-stem ordinal", note=ANUS)],
    "gajānanam": [sub("gajānana", "Gajānana — the elephant-faced one", "m", 2, "eka",
                      "bahuvrīhi a-stem")],
    "dvādaśaitāni": [sub("dvādaśan", "twelve", "n", 1, "bahu", "numeral (dvādaśan)"),
                     sub("etad", "these", "n", 1, "bahu", "pronominal (etad)",
                         note="dvādaśa + etāni → dvādaśaitāni")],
    "nāmāni": [sub("nāman", "names", "n", 1, "bahu", "consonant stem (-man)")],
    "trisandhyaṁ": [avy("trisandhyam", "at the three junctions of the day",
                        note="adverbial accusative, tri + sandhyā")],
    "yaḥ": [sub("yad", "whoever", "m", 1, "eka", "pronominal (yad)")],
    "yas": [sub("yad", "whoever", "m", 1, "eka", "pronominal (yad)",
                note="yaḥ → yas before the following s-")],
    "paṭhen": [tin("paṭh", "may recite, should recite", gana="1 (bhvādi)",
                   lakara="liṅ (opt.)", pur=3, vac="eka",
                   note="paṭhet → paṭhen before n-")],
    "naraḥ": [sub("nara", "a person, a man", "m", 1, "eka", "a-stem")],
    "vighnabhayan": [sub("vighnabhaya", "fear of obstacles", "n", 1, "eka",
                         "a-stem (vighna + bhaya)", note=ANUS)],
    "sarvasiddhikaram": [sub("sarvasiddhikara", "bringing about every accomplishment",
                             "n", 1, "eka", "a-stem (sarva + siddhi + kara)")],
    "prabho": [sub("prabhu", "O Lord", "m", 8, "eka", "u-stem")],
    "vidyārthī": [sub("vidyārthin", "one who seeks knowledge", "m", 1, "eka",
                      "in-stem (vidyā + arthin)")],
    "labhate": [tin("labh", "obtains, gains", gana="1 (bhvādi)",
                    lakara="laṭ", pur=3, vac="eka", note="ātmanepada")],
    "vidyān": [sub("vidyā", "knowledge, learning", "f", 2, "eka", "ā-stem", note=ANUS)],
    "dhanārthī": [sub("dhanārthin", "one who seeks wealth", "m", 1, "eka",
                      "in-stem (dhana + arthin)")],
    "dhanam": [sub("dhana", "wealth", "n", 2, "eka", "a-stem")],
    "putrārthī": [sub("putrārthin", "one who seeks sons", "m", 1, "eka",
                      "in-stem (putra + arthin)")],
    "putrān": [sub("putra", "sons", "m", 2, "bahu", "a-stem")],
    "mokṣārthī": [sub("mokṣārthin", "one who seeks liberation", "m", 1, "eka",
                      "in-stem (mokṣa + arthin)")],
    "gatim": [sub("gati", "the goal, the final course", "f", 2, "eka", "i-stem")],
    "japed": [tin("jap", "let one recite", gana="1 (bhvādi)", lakara="liṅ (opt.)",
                  pur=3, vac="eka", note="japet → japed before a voiced sound")],
    "gaṇapatistotraṁ": [sub("gaṇapatistotra", "the hymn to Gaṇapati", "n", 2, "eka",
                            "a-stem (gaṇapati + stotra)")],
    "ṣaḍbhir": [sub("ṣaṣ", "by six", "m", 3, "bahu", "numeral (ṣaṣ)",
                    note="ṣaḍbhiḥ → ṣaḍbhir before a voiced sound")],
    "māsaiḥ": [sub("māsa", "by months", "m", 3, "bahu", "a-stem")],
    "phalaṁ": [sub("phala", "the fruit, the result", "n", 2, "eka", "a-stem")],
    "labhet": [tin("labh", "he would obtain", gana="1 (bhvādi)", lakara="liṅ (opt.)",
                   pur=3, vac="eka")],
    "saṁvatsareṇa": [sub("saṁvatsara", "within a year", "m", 3, "eka", "a-stem",
                         note="instrumental of duration")],
    "siddhiñ": [sub("siddhi", "accomplishment, attainment", "f", 2, "eka", "i-stem",
                    note=ANUS)],
    "nātra": [NA, avy("atra", "here, in this matter", note="na + atra → nātra")],
    "saṁśayaḥ": [sub("saṁśaya", "doubt", "m", 1, "eka", "a-stem")],
    "aṣṭabhyo": [sub("aṣṭan", "to eight", "m", 4, "bahu", "numeral (aṣṭan)",
                     note="aṣṭabhyaḥ → aṣṭabhyo before a voiced sound")],
    "brāhmaṇebhyaś": [sub("brāhmaṇa", "to brāhmaṇas", "m", 4, "bahu", "a-stem",
                          note="brāhmaṇebhyaḥ → brāhmaṇebhyaś before c-")],
    "likhitvā": [avy("likhitvā", "having written (it) out",
                     note="gerund (ktvā) of √likh")],
    "samarpayet": [SAM, tin("ṛ", "let one present, let one offer",
                            gana="1 (bhvādi)", lakara="liṅ (opt.)",
                            pur=3, vac="eka", note="sam + √ṛ, causative")],
    "vidyā": [sub("vidyā", "knowledge, learning", "f", 1, "eka", "ā-stem")],
    "bhavet": [tin("bhū", "would become, would be", gana="1 (bhvādi)",
                   lakara="liṅ (opt.)", pur=3, vac="eka")],
    "sarvā": [sub("sarva", "all, entire", "f", 1, "eka", "pronominal a-stem, fem. -ā",
                  note="agrees with vidyā")],
    "gaṇeśasya": [sub("gaṇeśa", "of Gaṇeśa", "m", 6, "eka", "a-stem")],
    "prasādataḥ": [avy("prasādataḥ", "by the grace (of)",
                       note="prasāda + the ablative suffix -tas")],
    "śrīnāradapurāṇe": [sub("nāradapurāṇa", "in the Śrī Nārada Purāṇa", "n", 7, "eka",
                            "a-stem",
                            note="the honorific śrī- is dropped from the lemma so the "
                                 "dictionary link resolves")],
    "saṅkaṭanāśanagaṇeśastotraṁ": [sub("saṅkaṭanāśanagaṇeśastotra",
                                       "the Gaṇeśa hymn that destroys difficulty",
                                       "n", 1, "eka",
                                       "a-stem (saṅkaṭa + nāśana + gaṇeśa + stotra)")],
    "sampūrṇam": [sub("sampūrṇa", "complete, ended", "n", 1, "eka",
                      "past participle of sam-√pṝ")],

    # ── concluding · kṣamā prārthanā ──────────────────────────────────────
    "mantrahīnaṅ": [sub("mantrahīna", "wanting in mantras", "n", 1, "eka", "a-stem",
                        note="predicative to the nominative (yat) pūjitam; " + ANUS)],
    "kriyāhīnam": [sub("kriyāhīna", "wanting in the proper ritual acts", "n", 1, "eka",
                       "a-stem", note="predicative to the nominative (yat) pūjitam")],
    "bhaktihīnaṁ": [sub("bhaktihīna", "wanting in devotion", "n", 1, "eka", "a-stem",
                        note="predicative to the nominative (yat) pūjitam")],
    "maheśvara": [sub("maheśvara", "O Maheśvara, O great Lord", "m", 8, "eka", "a-stem")],
    "yat": [sub("yad", "whatever", "n", 1, "eka", "pronominal (yad)")],
    "pūjitaṁ": [sub("pūjita", "what has been worshipped — the worship performed",
                    "n", 1, "eka", "past participle of √pūj")],
    "mayā": [sub("asmad", "by me", None, 3, "eka", "pronominal (asmad)")],
    "deva": [sub("deva", "O Lord", "m", 8, "eka", "a-stem")],
    "paripūrṇan": [sub("paripūrṇa", "complete, whole", "n", 1, "eka",
                       "past participle of pari-√pṝ", note=ANUS)],
    "tad": [sub("tad", "that", "n", 1, "eka", "pronominal (tad)")],
    "astu": [ASTU],

    # ── concluding · udvāsanam ────────────────────────────────────────────
    "asmād": [sub("idam", "from this", "n", 5, "eka", "pronominal (idam)",
                  note="asmāt → asmād before a voiced sound")],
    "bimbād": [sub("bimba", "from the image", "n", 5, "eka", "a-stem",
                   note="bimbāt → bimbād before a voiced sound")],
    "āvāhitaṁ": [sub("āvāhita", "invoked, invited in", "m", 2, "eka",
                     "past participle of the causative of ā-√vah")],
    # `śrī devaṁ` is written as two words in the udvāsana, as it is in the
    # āvāhana, so the deity is a variable slot there too. Before y- the anusvāra
    # stays ṁ (it assimilates only before a stop), hence this surface beside the
    # `devan` of `devaṁ dhyāyāmi`.
    "devaṁ": [sub("deva", DEVA_ACC, "m", 2, "eka", "a-stem")],
    "yathāsthānam": [avy("yathāsthānam", "back to his own place",
                         note="adverbial accusative, yathā + sthāna")],
    "pratiṣṭhāpayāmi": [PRATI, tin("sthā", "I install again, I re-establish",
                                   gana="1 (bhvādi)",
                                   lakara="laṭ", pur=1, vac="eka",
                                   note="prati + √sthā, causative sthāpayati 'to establish'")],

    # ── concluding · samarpaṇam ───────────────────────────────────────────
    "kāyena": [sub("kāya", "with the body", "m", 3, "eka", "a-stem")],
    "vācā": [sub("vāc", "with speech", "f", 3, "eka", "consonant stem (vāc)")],
    "manasendriyair": [sub("manas", "with the mind", "n", 3, "eka", "consonant stem (-as)"),
                       sub("indriya", "with the senses", "n", 3, "bahu", "a-stem",
                           note="manasā + indriyaiḥ → manasendriyaiḥ; final visarga → r before v-")],
    "buddhyātmanā": [sub("buddhi", "with the intellect", "f", 3, "eka", "i-stem"),
                     sub("ātman", "with the self", "m", 3, "eka", "consonant stem (-man)",
                         note="buddhyā + ātmanā → buddhyātmanā")],
    "prakṛtes": [sub("prakṛti", "of (one's own) nature", "f", 6, "eka", "i-stem",
                     note="prakṛteḥ → prakṛtes before s-")],
    "svabhāvāt": [sub("svabhāva", "from (one's) own disposition", "m", 5, "eka", "a-stem")],
    "karomi": [tin("kṛ", "I do", gana="8 (tanādi)", lakara="laṭ", pur=1, vac="eka")],
    "yadyat": [sub("yad", "whatever", "n", 2, "eka", "pronominal (yad)"),
               sub("yad", "…whatever", "n", 2, "eka", "pronominal (yad)",
                   note="yat yat — distributive repetition, 'whatsoever'")],
    "sakalam": [sub("sakala", "the whole of it", "n", 2, "eka", "a-stem")],
    "parasmai": [sub("para", "to the supreme (being)", "m", 4, "eka",
                     "pronominal a-stem")],
    "nārāyaṇāyeti": [sub("nārāyaṇa", "to Nārāyaṇa", "m", 4, "eka", "a-stem"),
                     avy("iti", "thus — with that thought",
                         note="nārāyaṇāya + iti → nārāyaṇāyeti")],

    # ── concluding · oṁ tat sat ───────────────────────────────────────────
    "tatsat": [sub("tad", "that", "n", 1, "eka", "pronominal (tad)"),
               sub("sat", "the real, that which is", "n", 1, "eka",
                   "consonant stem (pres. part. of √as)",
                   note="oṁ tat sat — the threefold designation of Brahman")],
    "brahmārpaṇam": [sub("brahmārpaṇa", "an offering to Brahman", "n", 1, "eka",
                         "a-stem (brahman + arpaṇa)")],

    # ── abhiṣeka (optional expansion of step 7) ───────────────────────────
    # Vedic saṁhitā material. Every parse below is of the form the TAITTIRĪYA
    # recension actually reads, which is sometimes not the Ṛgvedic form
    # (vṛṣṇiyam, dadhikrāvṇṇo, utoṣasi) — see each section's `source`.
    "ā": [AA],
    "pyāyasva": [tin("pyai", "swell, be full", gana="1 (bhvādi)", lakara="loṭ",
                     pur=2, vac="eka", note="ā-√pyai, ātmanepada imperative")],
    "sametu": [SAM, tin("i", "let it come", gana="2 (adādi)", lakara="loṭ",
                        pur=3, vac="eka", note="sam + √i")],
    "viśvatas": [avy("viśvatas", "from every side",
                     note="viśvataḥ → viśvatas before s-")],
    "soma": [sub("soma", "O Soma", "m", 8, "eka", "a-stem")],
    "vṛṣṇiyam": [sub("vṛṣṇya", "bull-strength, manly vigour", "n", 1, "eka", "a-stem",
                     note="the Taittirīya spells it vṛṣṇiyam (three syllables); "
                          "the Ṛgveda has vṛṣṇyam — the same word")],
    "bhavā": [tin("bhū", "be!", gana="1 (bhvādi)", lakara="loṭ", pur=2, vac="eka",
                  note="bhava with the Vedic lengthening of the final vowel")],
    "vājasya": [sub("vāja", "of the prize, of the contest", "m", 6, "eka", "a-stem")],
    "saṅgathe": [sub("saṅgatha", "at the coming-together, at the winning", "m", 7,
                     "eka", "a-stem", note="sam + √gam")],

    "dadhikrāvṇṇo": [sub("dadhikrāvan", "of Dadhikrāvan — the divine steed", "m", 6,
                         "eka", "consonant stem (-van)",
                         note="dadhikrāvṇaḥ → -o before a vowel; the Taittirīya "
                              "geminates, dadhikrāvṇṇo, where the Ṛgveda has dadhikrāvṇo")],
    "akāriṣañ": [tin("kṛ", "I have made, I have sung", gana="8 (tanādi)",
                     lakara="luṅ (aorist)", pur=1, vac="eka",
                     note="akāriṣam; the anusvāra assimilates to ñ before j-")],
    "jiṣṇor": [sub("jiṣṇu", "of the conquering one", "m", 6, "eka", "u-stem",
                   note="jiṣṇoḥ → jiṣṇor before a vowel")],
    "aśvasya": [sub("aśva", "of the horse", "m", 6, "eka", "a-stem")],
    "vājinaḥ": [sub("vājin", "of the swift one, of the prize-winner", "m", 6, "eka",
                    "consonant stem (-in)")],
    "surabhi": [sub("surabhi", "fragrant", "n", 2, "eka", "i-stem",
                    note="predicative accusative with karat")],
    "no": [sub("asmad", "our, for us", None, 6, "bahu", "pronominal (asmad)",
               note="enclitic naḥ → no before a voiced sound")],
    "mukhā": [sub("mukha", "mouths", "n", 2, "bahu", "a-stem",
                  note="Vedic -ā for the classical -āni")],
    "karat": [tin("kṛ", "may he make", gana="8 (tanādi)", lakara="leṭ (subjunctive)",
                  pur=3, vac="eka", note="the Vedic subjunctive")],
    "praṇa": [PRA, sub("asmad", "for us", None, 6, "bahu", "pronominal (asmad)",
                       note="pra naḥ; the n retroflexes to ṇ after the r of pra")],
    "āyūṁṣi": [sub("āyus", "lives, life-spans", "n", 2, "bahu",
                   "consonant stem (-us)")],
    "tāriṣat": [tin("tṝ", "may he carry across, may he lengthen", gana="1 (bhvādi)",
                    lakara="leṭ (subjunctive)", pur=3, vac="eka")],

    "śukramasi": [sub("śukra", "bright, clear", "n", 1, "eka", "a-stem"),
                  tin("as", "you are", gana="2 (adādi)", lakara="laṭ", pur=2, vac="eka",
                      note="śukram asi")],
    "jyotirasi": [sub("jyotis", "light", "n", 1, "eka", "consonant stem (-is)"),
                  tin("as", "you are", gana="2 (adādi)", lakara="laṭ", pur=2, vac="eka",
                      note="jyotiḥ → jyotir before a vowel")],
    "tejo'si": [sub("tejas", "radiance, brilliance", "n", 1, "eka",
                    "consonant stem (-as)"),
                tin("as", "you are", gana="2 (adādi)", lakara="laṭ", pur=2, vac="eka",
                    note="tejaḥ + asi → tejo 'si, the a elided and written with an avagraha")],
    "vas": [sub("yuṣmad", "you (plural)", None, 2, "bahu", "pronominal (yuṣmad)",
                note="enclitic vaḥ → vas before s-")],
    "savitotpunātvacchidreṇa": [
        sub("savitṛ", "Savitṛ, the impeller — the sun as the quickener", "m", 1, "eka",
            "consonant stem (-tṛ)", note="savitā + ut → savitot"),
        upa("ut", "up, out — here of purifying upward"),
        tin("pū", "let him purify", gana="9 (kryādi)", lakara="loṭ", pur=3, vac="eka",
            note="ut + √pū; punātu + acchidreṇa → punātv acchidreṇa"),
        sub("acchidra", "with a flawless one, with one without a gap", "n", 3, "eka",
            "a-stem")],
    "pavitreṇa": [sub("pavitra", "with a strainer, with a purifier", "n", 3, "eka",
                      "a-stem")],
    "vasos": [sub("vasu", "of the good one, of the bright one", "m", 6, "eka", "u-stem",
                  note="vasoḥ → vasos before s-")],
    "sūryasya": [sub("sūrya", "of the sun", "m", 6, "eka", "a-stem")],
    "raśmibhiḥ": [sub("raśmi", "with the rays", "m", 3, "bahu", "i-stem")],

    "madhu": [sub("madhu", "sweet, honey — here adverbial, 'sweetly'", "n", 1, "eka",
                  "u-stem")],
    "vātā": [sub("vāta", "the winds", "m", 1, "bahu", "a-stem",
                 note="vātāḥ → vātā before a vowel")],
    "ṛtāyate": [sub("ṛtāyat", "for the one who keeps ṛta", "m", 4, "eka",
                    "present participle of the denominative ṛtāya-")],
    "kṣaranti": [tin("kṣar", "they flow", gana="1 (bhvādi)", lakara="laṭ", pur=3,
                     vac="bahu")],
    "sindhavaḥ": [sub("sindhu", "the rivers", "m", 1, "bahu", "u-stem")],
    "mādhvīrnas": [sub("mādhvī", "sweet (feminine)", "f", 1, "bahu", "ī-stem",
                       note="mādhvīḥ → mādhvīr before a voiced sound"),
                   sub("asmad", "for us", None, 4, "bahu", "pronominal (asmad)",
                       note="enclitic naḥ → nas before s-")],
    "santvoṣadhīḥ": [tin("as", "let them be", gana="2 (adādi)", lakara="loṭ", pur=3,
                         vac="bahu", note="santu + oṣadhīḥ → santv oṣadhīḥ"),
                     sub("oṣadhi", "the herbs, the plants", "f", 1, "bahu", "i-stem")],
    "naktamutoṣasi": [avy("naktam", "by night"),
                      avy("uta", "and, also"),
                      sub("uṣas", "at dawn", "f", 7, "eka", "consonant stem (-as)",
                          note="the Taittirīya locative utoṣasi; the Ṛgveda has the "
                               "ablative/genitive utoṣaso")],
    "madhumatpārthivaṁ": [sub("madhumat", "sweet, honeyed", "n", 1, "eka",
                              "consonant stem (-mat)"),
                          sub("pārthiva", "earthly", "n", 1, "eka", "a-stem")],
    "rajaḥ": [sub("rajas", "realm, expanse", "n", 1, "eka", "consonant stem (-as)")],
    "dyaurastu": [sub("div", "Heaven", "f", 1, "eka", "consonant stem (div/dyu)",
                      note="dyauḥ → dyaur before a vowel"),
                  ASTU],
    "naḥ": [sub("asmad", "us, for us, our", None, 2, "bahu", "pronominal (asmad)",
                note="enclitic")],
    "pitā": [sub("pitṛ", "father", "m", 1, "eka", "consonant stem (-tṛ)")],
    "madhumānno": [sub("madhumat", "sweet, honeyed", "m", 1, "eka",
                       "consonant stem (-mat)"),
                   sub("asmad", "for us", None, 4, "bahu", "pronominal (asmad)",
                       note="madhumān naḥ → madhumān no")],
    "vanaspatirmadhumām": [sub("vanaspati", "the forest tree", "m", 1, "eka", "i-stem",
                               note="vanaspatiḥ → vanaspatir before a voiced sound"),
                           sub("madhumat", "sweet, honeyed", "m", 1, "eka",
                               "consonant stem (-mat)",
                               note="madhumān → madhumāṁ before a vowel")],
    "sūryaḥ": [sub("sūrya", "the sun", "m", 1, "eka", "a-stem")],
    "mādhvīrgāvo": [sub("mādhvī", "sweet (feminine)", "f", 1, "bahu", "ī-stem"),
                    sub("go", "the cows", "f", 1, "bahu", "consonant stem (go)",
                        note="gāvaḥ → gāvo before a voiced sound")],
    "bhavantu": [tin("bhū", "let them be", gana="1 (bhvādi)", lakara="loṭ", pur=3,
                     vac="bahu")],

    "svāduḥ": [sub("svādu", "sweet", "m", 1, "eka", "u-stem")],
    "pavasva": [tin("pū", "flow clear!", gana="1 (bhvādi)", lakara="loṭ", pur=2,
                    vac="eka", note="ātmanepada; of Soma being clarified")],
    "divyāya": [sub("divya", "for the divine", "n", 4, "eka", "a-stem")],
    "janmane": [sub("janman", "for the race, for the birth", "n", 4, "eka",
                    "consonant stem (-man)")],
    "svādurindrāya": [sub("svādu", "sweet", "m", 1, "eka", "u-stem",
                          note="svāduḥ → svādur before a vowel"),
                      sub("indra", "for Indra", "m", 4, "eka", "a-stem")],
    "suhavītu": [oth("suhavītu", "well-invoked",
                     note="first member of suhavītu-nāman, 'whose name is well invoked'")],
    "nāmne": [sub("nāman", "for the one whose name…", "n", 4, "eka",
                  "consonant stem (-man)")],
    "svādurmitrāya": [sub("svādu", "sweet", "m", 1, "eka", "u-stem",
                          note="svāduḥ → svādur before a voiced sound"),
                      sub("mitra", "for Mitra", "m", 4, "eka", "a-stem")],
    "varuṇāya": [sub("varuṇa", "for Varuṇa", "m", 4, "eka", "a-stem")],
    "vāyave": [sub("vāyu", "for Vāyu", "m", 4, "eka", "u-stem")],
    "bṛhaspataye": [sub("bṛhaspati", "for Bṛhaspati", "m", 4, "eka", "i-stem")],
    "madhumām": [sub("madhumat", "sweet, honeyed", "m", 1, "eka",
                     "consonant stem (-mat)",
                     note="madhumān → madhumāṁ before a vowel")],
    "adābhyaḥ": [sub("adābhya", "not to be harmed, not to be deceived", "m", 1, "eka",
                     "a-stem")],
    "pañcāmṛta": [oth("pañcāmṛta", "the five nectars — milk, curd, ghee, honey, sugar",
                      note="first member of pañcāmṛta-snāna")],

    "yāḥ": [sub("yad", "those which", "f", 1, "bahu", "pronominal (yad)")],
    "phalinīryā": [sub("phalinī", "fruit-bearing", "f", 1, "bahu", "ī-stem",
                       note="phalinīḥ → phalinīr before a vowel"),
                   sub("yad", "those which", "f", 1, "bahu", "pronominal (yad)",
                       note="yāḥ → yā before a vowel")],
    "aphalā": [sub("aphala", "fruitless", "f", 1, "bahu", "a-stem",
                   note="aphalāḥ → aphalā before a vowel")],
    "apuṣpā": [sub("apuṣpa", "flowerless", "f", 1, "bahu", "a-stem")],
    "yāśca": [sub("yad", "those which", "f", 1, "bahu", "pronominal (yad)",
                  note="yāḥ → yāś before c-"),
              CA],
    "puṣpiṇīḥ": [sub("puṣpiṇī", "flowering", "f", 1, "bahu", "ī-stem")],
    "bṛhaspati": [oth("bṛhaspati", "Bṛhaspati, lord of prayer",
                      note="first member of bṛhaspati-prasūta, 'impelled by Bṛhaspati'")],
    "prasūtāstā": [sub("prasūta", "impelled, sent forth", "f", 1, "bahu",
                       "past participle of pra-√sū",
                       note="prasūtāḥ → prasūtās before t-"),
                   sub("tad", "they", "f", 1, "bahu", "pronominal (tad)",
                       note="tāḥ → tā before a voiced sound")],
    "muñcantvaṁhasaḥ": [tin("muc", "let them release", gana="6 (tudādi)", lakara="loṭ",
                            pur=3, vac="bahu",
                            note="muñcantu + aṁhasaḥ → muñcantv aṁhasaḥ"),
                        sub("aṁhas", "from distress, from anguish", "n", 5, "eka",
                            "consonant stem (-as)")],

    "āpo": [sub("ap", "O waters / the waters", "f", 1, "bahu", "consonant stem (ap)",
                note="āpaḥ → āpo before a voiced sound; nominative and vocative are alike")],
    "hiṣṭhā": [avy("hi", "indeed, for"),
               tin("as", "you are", gana="2 (adādi)", lakara="laṭ", pur=2, vac="bahu",
                   note="hi stha → hi ṣṭha, with the Vedic lengthening ṣṭhā")],
    "mayo": [oth("mayas", "refreshment, well-being",
                 note="first member of mayobhu, 'bringing well-being'; mayaḥ → mayo")],
    "bhuvastā": [sub("bhū", "bringing (well-being)", "f", 1, "bahu",
                     "root noun -bhū, in the compound mayobhu",
                     note="bhuvaḥ → bhuvas before t-"),
                 sub("tad", "you, those", "f", 1, "bahu", "pronominal (tad)")],
    "ūrje": [sub("ūrj", "for vigour, for nourishment", "f", 4, "eka",
                 "consonant stem (ūrj)")],
    "dadhātana": [tin("dhā", "set, place!", gana="3 (juhotyādi)", lakara="loṭ", pur=2,
                      vac="bahu", note="the Vedic 2nd-plural imperative in -tana")],
    "mahe": [sub("mahat", "for the great", "n", 4, "eka", "consonant stem (-at)")],
    "raṇāya": [sub("raṇa", "for delight, for joy", "m", 4, "eka", "a-stem")],
    "cakṣase": [tin("cakṣ", "to look upon", gana="2 (adādi)", lakara="—", pur=None,
                    vac=None, note="Vedic dative infinitive")],

    "yo": [sub("yad", "which", "m", 1, "eka", "pronominal (yad)",
               note="yaḥ → yo before a voiced sound")],
    "vaś": [sub("yuṣmad", "of you (plural)", None, 6, "bahu", "pronominal (yuṣmad)",
                note="enclitic vaḥ → vaś before ś-")],
    "śivatamo": [sub("śivatama", "most kindly, most auspicious", "m", 1, "eka",
                     "a-stem superlative of śiva")],
    "rasastasya": [sub("rasa", "sap, essence", "m", 1, "eka", "a-stem",
                       note="rasaḥ → rasas before t-"),
                   sub("tad", "of that", "m", 6, "eka", "pronominal (tad)")],
    "bhājayateha": [tin("bhaj", "give a share of, apportion", gana="1 (bhvādi)",
                        lakara="loṭ", pur=2, vac="bahu",
                        note="causative bhājayata + iha → bhājayateha"),
                    avy("iha", "here")],
    "uśatīriva": [sub("uśatī", "eager, willing", "f", 1, "bahu",
                      "feminine present participle of √vaś",
                      note="uśatīḥ → uśatīr before a vowel"),
                  avy("iva", "as, like")],
    "mātaraḥ": [sub("mātṛ", "mothers", "f", 1, "bahu", "consonant stem (-tṛ)")],

    "tasmā": [sub("tad", "to him", "m", 4, "eka", "pronominal (tad)",
                  note="tasmai → tasmā before a-")],
    "araṅ": [avy("aram", "readily, fittingly, enough",
                 note="aram → araṁ, and the anusvāra assimilates to ṅ before g-")],
    "gamāma": [tin("gam", "let us go", gana="1 (bhvādi)", lakara="leṭ (subjunctive)",
                   pur=1, vac="bahu")],
    "vo": [sub("yuṣmad", "you, to you (plural)", None, 2, "bahu", "pronominal (yuṣmad)",
               note="enclitic vaḥ → vo before a voiced sound")],
    "yasya": [sub("yad", "of whom, for whose", "m", 6, "eka", "pronominal (yad)")],
    "kṣayāya": [sub("kṣaya", "for the dwelling", "m", 4, "eka", "a-stem")],
    "jinvatha": [tin("jinv", "you quicken, you enliven", gana="1 (bhvādi)",
                     lakara="laṭ", pur=2, vac="bahu")],
    "janayathā": [tin("jan", "you beget", gana="4 (divādi)", lakara="laṭ", pur=2,
                      vac="bahu", note="causative janayatha, with Vedic lengthening")],

    # the offering formulae — the verb is the CAUSATIVE snapayāmi ("I cause to
    # bathe"), not the samarpayāmi the rest of the manual uses
    "snapayāmi": [tin("snā", "I bathe (you)", gana="2 (adādi)", lakara="laṭ", pur=1,
                      vac="eka", note="causative snapayati, 'to bathe another'")],
    "kṣīreṇa": [sub("kṣīra", "with milk", "n", 3, "eka", "a-stem")],
    "dadhnā": [sub("dadhi", "with curd", "n", 3, "eka", "i-stem")],
    "ājyena": [sub("ājya", "with ghee", "n", 3, "eka", "a-stem")],
    "madhunā": [sub("madhu", "with honey", "n", 3, "eka", "u-stem")],
    "śarkarayā": [sub("śarkarā", "with sugar", "f", 3, "eka", "ā-stem")],
    "phalodakena": [sub("phalodaka", "with fruit-water", "n", 3, "eka",
                        "a-stem (phala + udaka)")],
    "śuddhodakena": [sub("śuddhodaka", "with pure water", "n", 3, "eka",
                         "a-stem (śuddha + udaka)")],

    # ── vibhūti (Śaiva / smārta note beside gandha) ───────────────────────
    "tryambakaṁ": [sub("tryambaka", "the three-eyed one — Rudra", "m", 2, "eka",
                       "a-stem (tri + ambaka)")],
    "yajāmahe": [tin("yaj", "we worship, we offer to", gana="1 (bhvādi)",
                     lakara="laṭ", pur=1, vac="bahu", note="ātmanepada")],
    "sugandhim": [sub("sugandhi", "the fragrant one", "m", 2, "eka", "i-stem")],
    "puṣṭivardhanam": [sub("puṣṭivardhana", "the increaser of nourishment", "m", 2,
                           "eka", "a-stem (puṣṭi + vardhana)")],
    "urvārukamiva": [sub("urvāruka", "a cucumber", "n", 1, "eka", "a-stem"),
                     avy("iva", "as, like")],
    "bandhanānmṛtyormukṣīya": [
        sub("bandhana", "from its stalk, from its binding", "n", 5, "eka", "a-stem",
            note="bandhanāt → bandhanān before m-"),
        sub("mṛtyu", "from death", "m", 5, "eka", "u-stem",
            note="mṛtyoḥ → mṛtyor before a voiced sound"),
        tin("muc", "may I be freed", gana="6 (tudādi)", lakara="liṅ (optative)",
            pur=1, vac="eka", note="ātmanepada mukṣīya")],
    "mā'mṛtāt": [avy("mā", "not — the prohibitive particle"),
                 sub("amṛta", "from the deathless, from immortality", "n", 5, "eka",
                     "a-stem", note="mā + amṛtāt → mā 'mṛtāt")],

    "tryāyuṣañ": [sub("tryāyuṣa", "threefold life", "n", 2, "eka",
                      "a-stem (tri + āyus)",
                      note="the anusvāra assimilates to ñ before j-")],
    "tryāyuṣan": [sub("tryāyuṣa", "threefold life", "n", 2, "eka",
                      "a-stem (tri + āyus)", note=ANUS)],
    "tryāyuṣam": [sub("tryāyuṣa", "threefold life", "n", 2, "eka",
                      "a-stem (tri + āyus)")],
    "jamadagneḥ": [sub("jamadagni", "of Jamadagni — the ṛṣi", "m", 6, "eka",
                       "i-stem")],
    "kaśyapasya": [sub("kaśyapa", "of Kaśyapa — the ṛṣi", "m", 6, "eka", "a-stem")],
    "yaddevānān": [sub("yad", "whatever", "n", 1, "eka", "pronominal (yad)"),
                   sub("deva", "of the gods", "m", 6, "bahu", "a-stem",
                       note="devānām; the anusvāra assimilates before t-")],
    "tanme": [sub("tad", "that", "n", 1, "eka", "pronominal (tad)"),
              sub("asmad", "mine, to me", None, 6, "eka", "pronominal (asmad)",
                  note="enclitic me")],

    "agnir": [sub("agni", "fire", "m", 1, "eka", "i-stem",
                  note="agniḥ → agnir before a vowel")],
    "bhasma": [sub("bhasman", "ash", "n", 1, "eka", "consonant stem (-man)")],
    "vāyur": [sub("vāyu", "wind", "m", 1, "eka", "u-stem",
                  note="vāyuḥ → vāyur before a vowel")],
    "jalam": [sub("jala", "water", "n", 1, "eka", "a-stem")],
    "sthalam": [sub("sthala", "earth, dry land", "n", 1, "eka", "a-stem")],
    "vyometi": [sub("vyoman", "space, the sky", "n", 1, "eka",
                    "consonant stem (-man)", note="vyoma + iti → vyometi"),
                avy("iti", "thus — closing the quoted word")],
    "ha": [avy("ha", "indeed — an emphatic Vedic particle")],
    "idam": [sub("idam", "this, all this", "n", 1, "eka", "pronominal (idam)")],

    # --- the prokṣaṇa verse, Garuḍa Purāṇa 1.217.1–2 ----------------------
    # Two surfaces here are the marking engine's own output, not the received
    # spelling: `sarvāvasthāṁ` is keyed `sarvāvasthāṅ` (the anusvāra taking the
    # place of the following g-) and `bāhyābhyantaraḥ` is keyed
    # `bāhyābhyantaraś` (the visarga becoming ś before ś-).
    "apavitraḥ": [sub("apavitra", "impure, unclean", "m", 1, "eka", "a-stem",
                      note="negative a- + pavitra")],
    "pavitro": [sub("pavitra", "pure, clean", "m", 1, "eka", "a-stem",
                    note="pavitraḥ → pavitro before the voiced v- of vā")],
    "sarvāvasthāṅ": [sub("sarvāvasthā", "every condition, any state whatever",
                         "f", 2, "eka", "ā-stem",
                         note="sarva + avasthā; accusative of the state reached, "
                              "with gata. " + ANUS)],
    "gato'pi": [sub("gata", "gone, come to be", "m", 1, "eka",
                    "past participle of √gam",
                    note="gataḥ + api; the visarga becomes o before a-, and that "
                         "a- is then elided (marked by the avagraha)"),
                avy("api", "even, also")],
    "smaret": [tin("smṛ", "should remember, may call to mind",
                   gana="1 (bhvādi)", lakara="vidhi-liṅ", pur=3, vac="eka")],
    "puṇḍarīkākṣaṁ": [sub("puṇḍarīkākṣa", "the lotus-eyed one", "m", 2, "eka",
                          "a-stem",
                          note="puṇḍarīka (lotus) + akṣa (eye) — a name of Viṣṇu")],
    "sa": [sub("tad", "he, that one", "m", 1, "eka", "pronominal (tad)",
               note="saḥ → sa before a consonant")],
    "bāhyābhyantaraś": [sub("bāhyābhyantara", "outer and inner, without and within",
                            "m", 1, "eka", "a-stem",
                            note="bāhya + abhyantara; the visarga becomes ś "
                                 "before the following ś- (rendered in the "
                                 "change colour)")],
    "śuciḥ": [sub("śuci", "clean, pure", "m", 1, "eka", "i-stem")],

    # ── concluding · kṣamā prārthanā, the Devī and Śiva forms ─────────────
    # Lifted from VU's own sādhana (p. 66) and Śrī Rudram (p. 38). The two
    # prayers share most of their vocabulary — only the vocative changes —
    # so a surface that occurs in both is keyed once.
    "aparādha": [sub("aparādha", "offence, transgression", "m", None, None, "a-stem",
                     note="first member of aparādhasahasrāṇi / aparādhaśatam, "
                          "which VU prints as two words")],
    "sahasrāṇi": [sub("sahasra", "thousands", "n", 1, "bahu", "a-stem")],
    "kriyante'harniśaṁ": [tin("kṛ", "are done, are committed", gana="8 (tanādi)",
                              lakara="laṭ", pur=3, vac="bahu",
                              note="passive kriyante; aharniśam becomes 'harniśaṁ after e"),
                          avy("aharniśam", "day and night")],
    "dāso'yamiti": [sub("dāsa", "a servant", "m", 1, "eka", "a-stem",
                        note="dāsaḥ + ayam + iti, run together in the printed line"),
                    sub("idam", "this one", "m", 1, "eka", "pronominal (idam)"),
                    avy("iti", "thus — closing the words taken as said")],
    "māṁ": [sub("asmad", "me", None, 2, "eka", "pronominal (asmad)")],
    "mām": [sub("asmad", "me", None, 2, "eka", "pronominal (asmad)",
                note="māṁ becomes mām before p-")],
    "matvā": [avy("matvā", "having taken (me) to be",
                  note="gerund (ktvā) of √man")],
    "kṣamasva": [tin("kṣam", "forgive!", gana="1 (bhvādi)", lakara="loṭ",
                     pur=2, vac="eka", note="ātmanepada")],
    "parameśvari": [sub("parameśvarī", "O Supreme Empress", "f", 8, "eka", "ī-stem")],
    "parameśvara": [sub("parameśvara", "O Supreme Lord", "m", 8, "eka", "a-stem")],
    "sureśvari": [sub("sureśvarī", "O Empress of the gods", "f", 8, "eka", "ī-stem")],
    "sadāśiva": [sub("sadāśiva", "O Sadāśiva, the ever-auspicious", "m", 8, "eka",
                     "a-stem")],
    "āvāhanaṁ": [sub("āvāhana", "the inviting in, the invocation", "n", 2, "eka",
                     "a-stem (ā-√vah, causative)")],
    "jānāmi": [tin("jñā", "I know", gana="9 (kryādi)", lakara="laṭ", pur=1, vac="eka")],
    "visarjanam": [sub("visarjana", "the sending off, the taking of leave", "n", 2,
                       "eka", "a-stem (vi-√sṛj)")],
    "pūjāñ": [sub("pūjā", "worship", "f", 2, "eka", "ā-stem", note=ANUS)],
    "kṣamyatām": [tin("kṣam", "let it be pardoned", gana="1 (bhvādi)", lakara="loṭ",
                      pur=3, vac="eka", note="passive kṣamyatām")],
    "kṣamyatān": [tin("kṣam", "let it be pardoned", gana="1 (bhvādi)", lakara="loṭ",
                      pur=3, vac="eka", note="passive kṣamyatām; " + ANUS)],
    "pūjitam": [sub("pūjita", "what has been worshipped — the worship performed",
                    "n", 1, "eka", "past participle of √pūj",
                    note="pūjitaṁ becomes pūjitam before m-")],
    "tadastu": [sub("tad", "that", "n", 1, "eka", "pronominal (tad)"), ASTU],
    "śataṅ": [sub("śata", "a hundred", "n", 2, "eka", "a-stem", note=ANUS)],
    "kṛtvā": [avy("kṛtvā", "having done", note="gerund (ktvā) of √kṛ")],
    "jagadambeti": [sub("jagadambā", "Mother of the universe", "f", 1, "eka",
                        "ā-stem (jagat + ambā)",
                        note="jagadambā + iti, run together"),
                    avy("iti", "thus — marking the name as the word said")],
    "coccaret": [CA, upa("ud", "up, out"),
                 tin("car", "should utter, should pronounce", gana="1 (bhvādi)",
                     lakara="vidhiliṅ (opt.)", pur=3, vac="eka",
                     note="ca + ud-√car; ca uccaret becomes coccaret")],
    "yāṅ": [sub("yad", "which", "f", 2, "eka", "pronominal (yad)", note=ANUS)],
    "gatiṁ": [sub("gati", "the goal, the state reached", "f", 2, "eka", "i-stem")],
    "samavāpnoti": [SAM, upa("ava", "down, all the way"),
                    tin("āp", "reaches, obtains", gana="5 (svādi)", lakara="laṭ",
                        pur=3, vac="eka", note="sam + ava + √āp")],
    "tām": [sub("tad", "that", "f", 2, "eka", "pronominal (tad)",
                note="tāṁ becomes tām before b-")],
    "brahmādayas": [sub("brahmādi", "Brahmā and the rest", "m", 1, "bahu",
                        "i-stem (brahmā + ādi)",
                        note="brahmādayaḥ becomes brahmādayas before s-")],
    "surāḥ": [sub("sura", "the gods", "m", 1, "bahu", "a-stem")],
    "sāparādho'smi": [sub("sāparādha", "an offender, one who has offences", "m", 1,
                          "eka", "a-stem (sa + aparādha)",
                          note="sāparādhaḥ + asmi"),
                      tin("as", "I am", gana="2 (adādi)", lakara="laṭ", pur=1,
                          vac="eka")],
    "śaraṇam": [sub("śaraṇa", "refuge, shelter", "n", 2, "eka", "a-stem",
                    note="śaraṇaṁ becomes śaraṇam before p-")],
    "śaraṇaṁ": [sub("śaraṇa", "refuge, shelter", "n", 1, "eka", "a-stem")],
    "prāptas": [sub("prāpta", "having come, having arrived", "m", 1, "eka",
                    "past participle of pra-√āp",
                    note="prāptaḥ becomes prāptas before t-")],
    "tvāñ": [sub("yuṣmad", "you", None, 2, "eka", "pronominal (yuṣmad)", note=ANUS)],
    "jagadambike": [sub("jagadambikā", "O Mother of the universe", "f", 8, "eka",
                        "ā-stem")],
    "idānīmanukampyo'haṁ": [avy("idānīm", "now"),
                            sub("anukampya", "one to be pitied, deserving compassion",
                                "m", 1, "eka", "gerundive of anu-√kamp"),
                            sub("asmad", "I", None, 1, "eka", "pronominal (asmad)")],
    "yathecchasi": [avy("yathā", "in whatever way"),
                    tin("iṣ", "you wish", gana="6 (tudādi)", lakara="laṭ", pur=2,
                        vac="eka", note="yathā icchasi becomes yathecchasi")],
    "tathā": [avy("tathā", "so, in that way")],
    "ajñānād": [sub("ajñāna", "from ignorance", "n", 5, "eka", "a-stem (a + jñāna)",
                    note="ajñānāt becomes ajñānād before a voiced sound")],
    "vismṛter": [sub("vismṛti", "from forgetfulness", "f", 5, "eka", "i-stem",
                     note="vismṛteḥ becomes vismṛter before bh-")],
    "bhrāntyā": [sub("bhrānti", "through confusion", "f", 3, "eka", "i-stem")],
    "yan": [sub("yad", "what", "n", 1, "eka", "pronominal (yad)",
                note="yat becomes yan before n- — sandhi of the stop, not an anusvāra")],
    "nyūnamadhikaṅ": [sub("nyūna", "too little, left undone", "n", 1, "eka", "a-stem",
                          note="nyūnam + adhikam, run together"),
                      sub("adhika", "too much, done to excess", "n", 1, "eka",
                          "a-stem", note=ANUS)],
    "kṛtam": [sub("kṛta", "what has been done", "n", 1, "eka",
                  "past participle of √kṛ")],
    "sarvaṁ": [sub("sarva", "all of it", "n", 1, "eka", "pronominal adjective (sarva)")],
    "prasīda": [PRA, tin("sad", "be gracious!", gana="1 (bhvādi)", lakara="loṭ",
                         pur=2, vac="eka", note="pra + √sad")],
    "kāmeśvari": [sub("kāmeśvarī", "O Kāmeśvarī, mistress of what is desired",
                      "f", 8, "eka", "ī-stem")],
    "jaganmātas": [sub("jaganmātṛ", "O Mother of the world", "f", 8, "eka", "ṛ-stem",
                       note="jaganmātaḥ becomes jaganmātas before s-")],
    "saccidānanda": [sub("saccidānanda", "being, awareness and bliss", "m", None, None,
                         "a-stem (sat + cit + ānanda)",
                         note="first half of saccidānandavigrahā, printed apart")],
    "vigrahe": [sub("saccidānandavigrahā",
                    "O you whose very form is being, awareness and bliss",
                    "f", 8, "eka", "ā-stem",
                    note="second half of the compound, printed apart")],
    "gṛhāṇārcāmimām": [tin("grah", "take! receive!", gana="9 (kryādi)", lakara="loṭ",
                           pur=2, vac="eka", note="gṛhāṇa + arcām + imāṁ"),
                       sub("arcā", "worship, the act of worship", "f", 2, "eka",
                           "ā-stem"),
                       sub("idam", "this", "f", 2, "eka", "pronominal (idam)")],
    "prītyā": [sub("prīti", "with affection, gladly", "f", 3, "eka", "i-stem")],
    "guhyāti": [sub("guhya", "secret, to be kept hidden", "n", 1, "eka",
                    "gerundive of √guh",
                    note="guhya + ati + guhya + goptrī, 'guardian of the secret "
                         "beyond the secret'; VU prints the compound in pieces"),
                avy("ati", "beyond, surpassing")],
    "guhya": [sub("guhya", "secret, to be kept hidden", "n", None, None,
                  "gerundive of √guh")],
    "goptrī": [sub("goptrī", "she who guards, the protectress", "f", 1, "eka",
                   "ṛ-stem feminine (goptṛ)")],
    "tvaṅ": [sub("yuṣmad", "you", None, 1, "eka", "pronominal (yuṣmad)", note=ANUS)],
    "gṛhāṇāsmat": [tin("grah", "take! receive!", gana="9 (kryādi)", lakara="loṭ",
                       pur=2, vac="eka", note="gṛhāṇa + asmatkṛtaṁ"),
                   sub("asmad", "by us — first member of asmatkṛta, 'made by us'",
                       None, 5, "bahu", "pronominal (asmad)")],
    "kṛtañ": [sub("kṛta", "made, done", "n", 2, "eka", "past participle of √kṛ",
                  note="second half of asmatkṛtaṁ; " + ANUS)],
    "japam": [sub("japa", "the recitation, the muttered prayer", "m", 2, "eka",
                  "a-stem")],
    "siddhirbhavatu": [sub("siddhi", "attainment, accomplishment", "f", 1, "eka",
                           "i-stem", note="siddhiḥ becomes siddhir before bh-"),
                       tin("bhū", "let there be", gana="1 (bhvādi)", lakara="loṭ",
                           pur=3, vac="eka")],
    "tvat": [sub("yuṣmad", "from you, by your", None, 5, "eka", "pronominal (yuṣmad)",
                 note="first member of tvatprasādāt, printed apart")],
    "prasādāt": [sub("prasāda", "by the grace of", "m", 5, "eka",
                     "a-stem (pra-√sad)")],

    # ── the Vedic ṛc that opens the Śiva form (ṚV 1.114.1 = TS 4.5.10) ────
    "imām": [sub("idam", "this", "f", 2, "eka", "pronominal (idam)",
                 note="agrees with matim; before r- the final nasal is chanted "
                      "as the gum, imāgṁ")],
    "rudrāya": [sub("rudra", "to Rudra", "m", 4, "eka", "a-stem")],
    "tavase": [sub("tavas", "to the strong one", "m", 4, "eka",
                   "consonant stem (-as)")],
    "kapardine": [sub("kapardin", "to the one whose hair is braided", "m", 4, "eka",
                      "in-stem")],
    "kṣayad": [sub("kṣayadvīra", "to him who holds sway over heroes", "m", 4, "eka",
                   "a-stem (kṣayat, present participle of √kṣi, + vīra)",
                   note="first half of the compound, printed apart")],
    "vīrāya": [sub("kṣayadvīra", "to him who holds sway over heroes", "m", 4, "eka",
                   "a-stem", note="second half of the compound, printed apart")],
    "prabharāmahe": [PRA, tin("bhṛ", "we bring forward, we offer", gana="1 (bhvādi)",
                              lakara="laṭ", pur=1, vac="bahu",
                              note="pra + √bhṛ, ātmanepada")],
    "matim": [sub("mati", "thought — the prayer as it is conceived", "f", 2, "eka",
                  "i-stem")],
    "yathā": [avy("yathā", "so that")],
    "śam": [avy("śam", "well-being, peace",
                note="with √as: 'may there be well-being'")],
    "asad": [tin("as", "may there be", gana="2 (adādi)",
                 lakara="leṭ (Vedic subjunctive)", pur=3, vac="eka",
                 note="asat becomes asad before a voiced sound")],
    "dvipade": [sub("dvipad", "for the two-footed — for our people", "m", 4, "eka",
                    "consonant stem (dvi + pad)")],
    "catuṣpade": [sub("catuṣpad", "for the four-footed — for our animals", "m", 4,
                      "eka", "consonant stem (catur + pad)")],
    "viśvam": [sub("viśva", "everything, the whole of it", "n", 1, "eka",
                   "pronominal adjective (viśva)",
                   note="viśvaṁ becomes viśvam before p-")],
    "puṣṭaṅ": [sub("puṣṭa", "thriving, well-nourished", "n", 1, "eka",
                   "past participle of √puṣ", note=ANUS)],
    "grāme": [sub("grāma", "in the village", "m", 7, "eka", "a-stem")],
    "asminn": [sub("idam", "in this", "m", 7, "eka", "pronominal (idam)",
                   note="asmin becomes asminn before a vowel")],
    "anāturam": [sub("anātura", "free of sickness", "n", 1, "eka",
                     "a-stem (a + ātura)")],

    # ── the ślokas of the Śiva form ───────────────────────────────────────
    "pāpo'ham": [sub("pāpa", "sin; sinful", "m", 1, "eka", "a-stem",
                     note="pāpaḥ + ahaṁ"),
                 sub("asmad", "I", None, 1, "eka", "pronominal (asmad)")],
    "pāpakarmā'ham": [sub("pāpakarman", "one whose acts are sinful", "m", 1, "eka",
                          "consonant stem (-man)"),
                      sub("asmad", "I", None, 1, "eka", "pronominal (asmad)")],
    "pāpātmā": [sub("pāpātman", "one whose very self is sinful", "m", 1, "eka",
                    "consonant stem (-man)")],
    "pāpa": [sub("pāpa", "sin", "n", None, None, "a-stem",
                 note="first member of pāpasambhava, printed apart")],
    "sambhavaḥ": [sub("sambhava", "arising from, born of", "m", 1, "eka",
                      "a-stem (sam-√bhū)")],
    "trāhi": [tin("trai", "protect!", gana="1 (bhvādi)", lakara="loṭ", pur=2,
                  vac="eka")],
    "pārvatīnātha": [sub("pārvatīnātha", "O Lord of Pārvatī", "m", 8, "eka",
                         "a-stem")],
    "sarvapāpaharo": [sub("sarvapāpahara", "the remover of all sin", "m", 1, "eka",
                          "a-stem",
                          note="sarvapāpaharaḥ becomes sarvapāpaharo before bh-")],
    "bhava": [tin("bhū", "be!", gana="1 (bhvādi)", lakara="loṭ", pur=2, vac="eka")],
    "anyathā": [avy("anyathā", "otherwise, in any other way")],
    "nāsti": [NA, tin("as", "there is", gana="2 (adādi)", lakara="laṭ", pur=3,
                      vac="eka", note="na asti becomes nāsti")],
    "tvameva": [sub("yuṣmad", "you", None, 1, "eka", "pronominal (yuṣmad)"),
                avy("eva", "alone, and no other")],
    "mama": [sub("asmad", "my, mine", None, 6, "eka", "pronominal (asmad)")],
    "tasmāt": [avy("tasmāt", "therefore")],
    "kāruṇya": [sub("kāruṇya", "compassion", "n", None, None, "a-stem",
                    note="first member of kāruṇyabhāvena, printed apart")],

    # ── concluding · the Nārāyaṇa form (Youth Wing sādhanā) ───────────────
    # Its first two verses ask pardon for faults in the RECITATION — syllable,
    # word, measure, visarga, anusvāra — which is vocabulary no other form of
    # the prayer uses.
    "yadakṣarapadabhraṣṭaṁ": [sub("yad", "whatever", "n", 1, "eka", "pronominal (yad)",
                                  note="yat + akṣarapadabhraṣṭam, run together"),
                              sub("akṣarapadabhraṣṭa",
                                  "fallen away from its syllables and its words",
                                  "n", 1, "eka",
                                  "a-stem (akṣara + pada + bhraṣṭa, past participle "
                                  "of √bhraṁś)")],
    "mātrāhīnan": [sub("mātrāhīna", "wanting in its measure — a vowel not held its "
                       "length", "n", 1, "eka", "a-stem (mātrā + hīna)", note=ANUS)],
    "yad": [sub("yad", "whatever", "n", 1, "eka", "pronominal (yad)")],
    "nārāyaṇa": [sub("nārāyaṇa", "O Nārāyaṇa", "m", 8, "eka", "a-stem")],
    "visargabindumātrāṇi": [sub("visargabindumātra",
                                "visargas, anusvāras and vowel measures", "n", 2,
                                "bahu", "a-stem (visarga + bindu + mātra)")],
    "padapādākṣarāṇi": [sub("padapādākṣara", "words, pādas and syllables", "n", 2,
                            "bahu", "a-stem (pada + pāda + akṣara)")],
    "nyūnāni": [sub("nyūna", "too few, left short", "n", 2, "bahu", "a-stem")],
    "cātiriktāni": [CA, sub("atirikta", "too many, said in excess", "n", 2, "bahu",
                            "past participle of ati-√ric",
                            note="ca + atiriktāni")],
    "rakṣa": [tin("rakṣ", "protect!", gana="1 (bhvādi)", lakara="loṭ", pur=2,
                  vac="eka")],
}

# (verse-id, word-index) -> entries, for a surface whose parse is context-specific.
OVERRIDES = {
    # `dhiyo yo naḥ pracodayāt` — "who may impel OUR thoughts": genitive, where
    # the shared `naḥ` entry carries the accusative it has elsewhere.
    ("p-pranayama-gayatri", 9): [
        sub("asmad", "our", None, 6, "bahu", "pronominal (asmad)",
            note="enclitic genitive naḥ")],

    # The naivedya Gāyatrī is the SAME LINE as the prāṇāyāma's, so `naḥ` must
    # parse the same way in both. Without this it took the generic accusative
    # while the identical line above took the genitive.
    ("n-gayatri", 12): [
        sub("asmad", "our", None, 6, "bahu", "pronominal (asmad)",
            note="enclitic genitive naḥ")],

    # `tā na ūrje dadhātana` — this `na` is the enclitic asmad (naḥ → na before a
    # vowel), NOT the negative particle the same surface carries elsewhere.
    ("a-suddha-1", 4): [sub("asmad", "us, for us", None, 4, "bahu",
                            "pronominal (asmad)",
                            note="enclitic naḥ → na before a vowel")],
}
