#!/usr/bin/env node
/**
 * Generate every consumer of the design tokens.
 *
 * TWO INDEPENDENT AXES, and the CSS shape follows from that:
 *
 *   [data-chrome="palladio"][data-mode="light"]   the instrument
 *   [data-doc="warm"][data-mode="light"]          the page
 *
 * They are separate attributes on separate elements, so any chrome may be worn
 * with any document theme — thirty combinations from eleven entries, none of
 * them special-cased. A single combined theme would have needed thirty entries
 * and would still have been the wrong shape, because the two things answer to
 * different people at different moments: the shell to whoever is sitting there
 * for two hours, the page to whatever is being proofed.
 *
 * The typed source is the master and CSS is one of its outputs, not the other
 * way round. The platform this came from parsed a stylesheet to produce its
 * tokens, which leaves every non-CSS consumer — the Word style table, the print
 * sheet, Python tooling — downstream of a text parse.
 *
 *   node packages/tokens/gen.mjs
 *   node packages/tokens/gen.mjs --check    # exit 1 if anything would change
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'generated');
const check = process.argv.includes('--check');

const { BASE, MARK_GEOMETRY } = await import('./src/source.ts');
const { CHROME_THEMES, DEFAULT_CHROME } = await import('./src/chrome-themes.ts');
const { DOCUMENT_THEMES, DEFAULT_DOCUMENT } = await import('./src/document-themes.ts');

/**
 * The column-tracking coefficient for a fluid size, in `cqi`.
 *
 * Chosen so the role reaches its full size exactly at a full page's text
 * column and shrinks only below that. The inherited `3.1cqi` was tuned against
 * a card in the platform's reader, and once the document column became a real
 * container it put a 19.44 pt mantra line at 13.99 pt — smaller than the Word
 * theme it is meant to be the roomier alternative to.
 */
const cqiFor = (rem) => ((rem * 16) / ((WORD_PAGE.contentPt / 72) * 96)) * 100;


/*
 * The emitters live in `emit.mjs` — what a token IS for each axis. This file
 * is what a FILE looks like: the three generated artefacts and the `--check`
 * mode a gate runs.
 */
const {
  DENSITIES, MODES, chromeVars, decl, densityVars, documentVars, flatten, legacyAliases,
  typeVars,
} = await import('./emit.mjs');

/* The tokens that vary with nothing: the scale steps and the mark geometry.
   `color-*` and `doc-*` are excluded because those DO vary, per theme. */
const scaleVars = Object.fromEntries(
  Object.entries(BASE).filter(([k]) => !k.startsWith('color-') && !k.startsWith('doc-')),
);
const geometry = flatten(MARK_GEOMETRY, 'mark');

const css = `/* GENERATED by packages/tokens/gen.mjs. Do not edit.
 *
 * ${CHROME_THEMES.length} chrome themes x ${DOCUMENT_THEMES.length} document themes x ${MODES.length} modes.
 * Two independent attributes, so any shell may be worn with any page.
 *
 *   <html data-mode="light|dark">
 *   <div  data-chrome="palladio">   the instrument
 *   <div  data-doc="warm">          the page
 */

/* Scales, geometry and anything that does not vary by theme. */
:root {
  /* The document's zoom. The views override it on the column; the default is
     here so an unzoomed document — the measuring probe, a test's fragment —
     still resolves every length. */
  --doc-zoom: 1;
${decl({ ...scaleVars, ...geometry })}
}

/* The defaults, so an unthemed subtree is still legible. */
:root {
${decl(chromeVars(CHROME_THEMES.find((t) => t.id === DEFAULT_CHROME), 'light'))}
${decl(documentVars(DOCUMENT_THEMES.find((t) => t.id === DEFAULT_DOCUMENT), 'light'))}
${decl(typeVars(DOCUMENT_THEMES.find((t) => t.id === DEFAULT_DOCUMENT)))}
${decl(densityVars(CHROME_THEMES.find((t) => t.id === DEFAULT_CHROME).scale))}
${decl(legacyAliases())}
}
${DENSITIES.map((name) => `
[data-density="${name}"] {
${decl(densityVars(name))}
}`).join('')}
${CHROME_THEMES.flatMap((theme) => MODES.map((mode) => `
[data-chrome="${theme.id}"]${mode === 'light' ? ':not([data-mode="dark"])' : '[data-mode="dark"]'},
[data-mode="${mode}"] [data-chrome="${theme.id}"] {
${decl(chromeVars(theme, mode))}
${decl(legacyAliases())}
}`)).join('')}
${DOCUMENT_THEMES.map((theme) => `
/* ${theme.name} — the type scale (${theme.scale}), independent of the mode. */
[data-doc="${theme.id}"] {
${decl(typeVars(theme))}
}`).join('')}
${DOCUMENT_THEMES.flatMap((theme) => MODES.map((mode) => `
[data-doc="${theme.id}"]${mode === 'light' ? ':not([data-mode="dark"])' : '[data-mode="dark"]'},
[data-mode="${mode}"] [data-doc="${theme.id}"] {
${decl(documentVars(theme, mode))}
${decl(legacyAliases())}
}`)).join('')}
`;

// ── TypeScript ──────────────────────────────────────────────────────────────
const ts = `/* GENERATED by packages/tokens/gen.mjs. Do not edit. */

export const CHROME_IDS = ${JSON.stringify(CHROME_THEMES.map((t) => t.id))} as const;
export const DOCUMENT_IDS = ${JSON.stringify(DOCUMENT_THEMES.map((t) => t.id))} as const;
export const MODES = ${JSON.stringify(MODES)} as const;

export type ChromeId = (typeof CHROME_IDS)[number];
export type DocumentId = (typeof DOCUMENT_IDS)[number];
export type Mode = (typeof MODES)[number];

export const DEFAULT_CHROME = ${JSON.stringify(DEFAULT_CHROME)};
export const DEFAULT_DOCUMENT = ${JSON.stringify(DEFAULT_DOCUMENT)};

export const DENSITIES = ${JSON.stringify(DENSITIES)} as const;
export type Density = (typeof DENSITIES)[number];

/** Each chrome theme's default density, until the reader chooses one. */
export const CHROME_DENSITY: Readonly<Record<string, string>> = ${JSON.stringify(
  Object.fromEntries(CHROME_THEMES.map((t) => [t.id, t.scale])), null, 2)};

export const DENSITY_CHOICES = [
  { id: 'compact', name: 'Compact', note: 'The most on screen. Small controls, tight rows.' },
  { id: 'regular', name: 'Regular', note: 'The middle setting.' },
  { id: 'roomy', name: 'Roomy', note: 'Larger controls and more air. Easier at a distance.' },
];

/** What to show in a theme picker: id, name, and one line of why. */
export const CHROME_CHOICES = ${JSON.stringify(
  CHROME_THEMES.map((t) => ({ id: t.id, name: t.name, note: t.note })), null, 2)};

export const DOCUMENT_CHOICES = ${JSON.stringify(
  DOCUMENT_THEMES.map((t) => ({ id: t.id, name: t.name, note: t.note })), null, 2)};

/** Resolved values, for consumers that cannot read CSS (Word export, print). */
export const CHROME_TOKENS = ${JSON.stringify(
  Object.fromEntries(CHROME_THEMES.map((t) => [t.id,
    Object.fromEntries(MODES.map((m) => [m, chromeVars(t, m)]))])), null, 2)};

export const DOCUMENT_TOKENS = ${JSON.stringify(
  Object.fromEntries(DOCUMENT_THEMES.map((t) => [t.id,
    Object.fromEntries(MODES.map((m) => [m, documentVars(t, m)]))])), null, 2)};
`;

const json = JSON.stringify({
  generated: 'packages/tokens/gen.mjs',
  chromeThemes: CHROME_THEMES.map((t) => t.id),
  documentThemes: DOCUMENT_THEMES.map((t) => t.id),
  defaults: { chrome: DEFAULT_CHROME, document: DEFAULT_DOCUMENT },
  scales: scaleVars,
  markGeometry: MARK_GEOMETRY,
  chrome: Object.fromEntries(CHROME_THEMES.map((t) => [t.id,
    Object.fromEntries(MODES.map((m) => [m, chromeVars(t, m)]))])),
  document: Object.fromEntries(DOCUMENT_THEMES.map((t) => [t.id,
    Object.fromEntries(MODES.map((m) => [m, documentVars(t, m)]))])),
}, null, 2) + '\n';

const files = [['tokens.css', css], ['tokens.ts', ts], ['tokens.json', json]];

if (check) {
  let stale = 0;
  for (const [name, body] of files) {
    const path = join(OUT, name);
    if (!existsSync(path) || readFileSync(path, 'utf8') !== body) {
      console.error(`  stale: generated/${name}`);
      stale += 1;
    }
  }
  if (stale > 0) {
    console.error(`\n${stale} generated file(s) stale — run: npm run gen:tokens\n`);
    process.exit(1);
  }
  console.log(`tokens current — ${CHROME_THEMES.length} chrome x ${DOCUMENT_THEMES.length} document x ${MODES.length} modes`);
  process.exit(0);
}

mkdirSync(OUT, { recursive: true });
for (const [name, body] of files) writeFileSync(join(OUT, name), body);
console.log(`\n  ${CHROME_THEMES.length} chrome themes  ${DOCUMENT_THEMES.length} document themes  `
  + `${MODES.length} modes  = ${CHROME_THEMES.length * DOCUMENT_THEMES.length * MODES.length} combinations`);
console.log(`  ${Object.keys(geometry).length} geometry vars, ${Object.keys(scaleVars).length} scale tokens`);
console.log(`  -> ${OUT}\n`);
