#!/usr/bin/env node
/**
 * Generate every consumer of the design tokens from `src/source.ts`.
 *
 * The direction matters. The platform this code came from kept its tokens in a
 * CSS `@theme` block and PARSED the stylesheet to produce everything else,
 * which makes CSS the master and leaves any consumer that is not CSS — the Word
 * style table, the print sheet, Python tooling — downstream of a text parse.
 *
 * Here the typed source is the master and CSS is one of its outputs, so a
 * theme, a face or a colour is added in one place and reaches every surface by
 * construction rather than by discipline.
 *
 *   node packages/tokens/gen.mjs           # write
 *   node packages/tokens/gen.mjs --check   # exit 1 if anything would change
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'generated');
const check = process.argv.includes('--check');

const { BASE, FONTS, THEMES, DEFAULT_THEME, MARK_GEOMETRY } =
  await import('./src/source.ts');

/** A theme resolved to a complete set — never half-defined. */
const resolved = Object.fromEntries(
  Object.entries(THEMES).map(([name, t]) => [name, { ...BASE, ...t.patch }]),
);

const fontVars = Object.fromEntries(
  Object.entries(FONTS).map(([role, f]) => [`font-${role}`, f.stack.join(', ')]),
);

/** Mark geometry, flattened to custom properties: `--mark-holdStroke-short`. */
function flatten(obj, prefix, into = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = `${prefix}-${k}`;
    if (v !== null && typeof v === 'object') flatten(v, key, into);
    else into[key] = String(v);
  }
  return into;
}
const geometryVars = flatten(MARK_GEOMETRY, 'mark');

const decl = (vars, indent = '  ') =>
  Object.entries(vars).map(([k, v]) => `${indent}--${k}: ${v};`).join('\n');

// ── CSS ─────────────────────────────────────────────────────────────────────
const themeNames = Object.keys(THEMES);
const darkThemes = themeNames.filter((n) => THEMES[n].scheme === 'dark');
const schemeDefault = darkThemes[0];

const css = `/* GENERATED by packages/tokens/gen.mjs from src/source.ts. Do not edit.
 *
 * ${themeNames.length} themes, ${Object.keys(BASE).length} tokens, ${Object.keys(FONTS).length} font roles.
 *
 * Every theme is emitted COMPLETE rather than as a patch, so no rule depends on
 * cascade order to be correct and a half-defined theme is impossible.
 */

:root {
${decl({ ...resolved[DEFAULT_THEME], ...fontVars, ...geometryVars })}
}
${themeNames.map((n) => `
[data-theme="${n}"] {
${decl(resolved[n])}
}`).join('')}
${schemeDefault === undefined ? '' : `
/* No explicit choice: follow the system. Scoped so an explicit
   [data-theme] always wins, in both directions. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${decl(resolved[schemeDefault], '    ')}
  }
}`}
`;

// ── TypeScript ──────────────────────────────────────────────────────────────
const ts = `/* GENERATED by packages/tokens/gen.mjs from src/source.ts. Do not edit. */

export const THEME_NAMES = ${JSON.stringify(themeNames)} as const;
export type ThemeName = (typeof THEME_NAMES)[number];

/** Every theme, resolved to a complete set of values. */
export const TOKENS: Readonly<Record<ThemeName, Readonly<Record<string, string>>>> =
${JSON.stringify(resolved, null, 2)};

/** Font stacks by role, ready to assign to \`font-family\`. */
export const FONT_STACKS: Readonly<Record<string, string>> =
${JSON.stringify(fontVars, null, 2)};

/** Mark geometry as custom-property names and values. */
export const GEOMETRY_VARS: Readonly<Record<string, string>> =
${JSON.stringify(geometryVars, null, 2)};

/** Resolve one token in one theme. Throws rather than returning a blank. */
export function token(theme: ThemeName, name: string): string {
  const value = TOKENS[theme][name];
  if (value === undefined) {
    throw new Error(\`unknown token "\${name}" in theme "\${theme}"\`);
  }
  return value;
}
`;

// ── JSON, for the Python tooling ────────────────────────────────────────────
const json = JSON.stringify({
  generated: 'packages/tokens/gen.mjs',
  source: 'packages/tokens/src/source.ts',
  defaultTheme: DEFAULT_THEME,
  themes: resolved,
  fonts: fontVars,
  markGeometry: MARK_GEOMETRY,
}, null, 2) + '\n';

const files = [['tokens.css', css], ['tokens.ts', ts], ['tokens.json', json]];

if (check) {
  let stale = 0;
  for (const [name, body] of files) {
    const path = join(OUT, name);
    const got = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (got !== body) { console.error(`  stale: generated/${name}`); stale += 1; }
  }
  if (stale > 0) {
    console.error(`\n${stale} generated file(s) stale — run: npm run gen:tokens\n`);
    process.exit(1);
  }
  console.log(`tokens current — ${themeNames.length} themes, ${Object.keys(BASE).length} tokens, ${Object.keys(FONTS).length} faces`);
  process.exit(0);
}

mkdirSync(OUT, { recursive: true });
for (const [name, body] of files) writeFileSync(join(OUT, name), body);
console.log(`\n  ${themeNames.length} themes  ${Object.keys(BASE).length} tokens  ` +
  `${Object.keys(FONTS).length} faces  ${Object.keys(geometryVars).length} geometry vars`);
console.log(`  -> ${resolve(OUT)}\n`);
